// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: promotionMessage.proto

package waldo_protobuffs;

public final class PromotionProto {
  private PromotionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PromotionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .UUID event_uuid = 1;
    boolean hasEventUuid();
    waldo_protobuffs.UtilProto.UUID getEventUuid();
    waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder();
    
    // required .Priority new_priority = 2;
    boolean hasNewPriority();
    waldo_protobuffs.UtilProto.Priority getNewPriority();
    waldo_protobuffs.UtilProto.PriorityOrBuilder getNewPriorityOrBuilder();
  }
  public static final class Promotion extends
      com.google.protobuf.GeneratedMessage
      implements PromotionOrBuilder {
    // Use Promotion.newBuilder() to construct.
    private Promotion(Builder builder) {
      super(builder);
    }
    private Promotion(boolean noInit) {}
    
    private static final Promotion defaultInstance;
    public static Promotion getDefaultInstance() {
      return defaultInstance;
    }
    
    public Promotion getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return waldo_protobuffs.PromotionProto.internal_static_Promotion_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return waldo_protobuffs.PromotionProto.internal_static_Promotion_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .UUID event_uuid = 1;
    public static final int EVENT_UUID_FIELD_NUMBER = 1;
    private waldo_protobuffs.UtilProto.UUID eventUuid_;
    public boolean hasEventUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public waldo_protobuffs.UtilProto.UUID getEventUuid() {
      return eventUuid_;
    }
    public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
      return eventUuid_;
    }
    
    // required .Priority new_priority = 2;
    public static final int NEW_PRIORITY_FIELD_NUMBER = 2;
    private waldo_protobuffs.UtilProto.Priority newPriority_;
    public boolean hasNewPriority() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public waldo_protobuffs.UtilProto.Priority getNewPriority() {
      return newPriority_;
    }
    public waldo_protobuffs.UtilProto.PriorityOrBuilder getNewPriorityOrBuilder() {
      return newPriority_;
    }
    
    private void initFields() {
      eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      newPriority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasEventUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNewPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEventUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getNewPriority().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, newPriority_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, eventUuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, newPriority_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static waldo_protobuffs.PromotionProto.Promotion parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(waldo_protobuffs.PromotionProto.Promotion prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements waldo_protobuffs.PromotionProto.PromotionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return waldo_protobuffs.PromotionProto.internal_static_Promotion_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return waldo_protobuffs.PromotionProto.internal_static_Promotion_fieldAccessorTable;
      }
      
      // Construct using waldo_protobuffs.PromotionProto.Promotion.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventUuidFieldBuilder();
          getNewPriorityFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (newPriorityBuilder_ == null) {
          newPriority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
        } else {
          newPriorityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return waldo_protobuffs.PromotionProto.Promotion.getDescriptor();
      }
      
      public waldo_protobuffs.PromotionProto.Promotion getDefaultInstanceForType() {
        return waldo_protobuffs.PromotionProto.Promotion.getDefaultInstance();
      }
      
      public waldo_protobuffs.PromotionProto.Promotion build() {
        waldo_protobuffs.PromotionProto.Promotion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private waldo_protobuffs.PromotionProto.Promotion buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        waldo_protobuffs.PromotionProto.Promotion result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public waldo_protobuffs.PromotionProto.Promotion buildPartial() {
        waldo_protobuffs.PromotionProto.Promotion result = new waldo_protobuffs.PromotionProto.Promotion(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (eventUuidBuilder_ == null) {
          result.eventUuid_ = eventUuid_;
        } else {
          result.eventUuid_ = eventUuidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (newPriorityBuilder_ == null) {
          result.newPriority_ = newPriority_;
        } else {
          result.newPriority_ = newPriorityBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof waldo_protobuffs.PromotionProto.Promotion) {
          return mergeFrom((waldo_protobuffs.PromotionProto.Promotion)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(waldo_protobuffs.PromotionProto.Promotion other) {
        if (other == waldo_protobuffs.PromotionProto.Promotion.getDefaultInstance()) return this;
        if (other.hasEventUuid()) {
          mergeEventUuid(other.getEventUuid());
        }
        if (other.hasNewPriority()) {
          mergeNewPriority(other.getNewPriority());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasEventUuid()) {
          
          return false;
        }
        if (!hasNewPriority()) {
          
          return false;
        }
        if (!getEventUuid().isInitialized()) {
          
          return false;
        }
        if (!getNewPriority().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              waldo_protobuffs.UtilProto.UUID.Builder subBuilder = waldo_protobuffs.UtilProto.UUID.newBuilder();
              if (hasEventUuid()) {
                subBuilder.mergeFrom(getEventUuid());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEventUuid(subBuilder.buildPartial());
              break;
            }
            case 18: {
              waldo_protobuffs.UtilProto.Priority.Builder subBuilder = waldo_protobuffs.UtilProto.Priority.newBuilder();
              if (hasNewPriority()) {
                subBuilder.mergeFrom(getNewPriority());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNewPriority(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .UUID event_uuid = 1;
      private waldo_protobuffs.UtilProto.UUID eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> eventUuidBuilder_;
      public boolean hasEventUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public waldo_protobuffs.UtilProto.UUID getEventUuid() {
        if (eventUuidBuilder_ == null) {
          return eventUuid_;
        } else {
          return eventUuidBuilder_.getMessage();
        }
      }
      public Builder setEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventUuid_ = value;
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setEventUuid(
          waldo_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = builderForValue.build();
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeEventUuid(waldo_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              eventUuid_ != waldo_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            eventUuid_ =
              waldo_protobuffs.UtilProto.UUID.newBuilder(eventUuid_).mergeFrom(value).buildPartial();
          } else {
            eventUuid_ = value;
          }
          onChanged();
        } else {
          eventUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearEventUuid() {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = waldo_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public waldo_protobuffs.UtilProto.UUID.Builder getEventUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEventUuidFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
        if (eventUuidBuilder_ != null) {
          return eventUuidBuilder_.getMessageOrBuilder();
        } else {
          return eventUuid_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder> 
          getEventUuidFieldBuilder() {
        if (eventUuidBuilder_ == null) {
          eventUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.UUID, waldo_protobuffs.UtilProto.UUID.Builder, waldo_protobuffs.UtilProto.UUIDOrBuilder>(
                  eventUuid_,
                  getParentForChildren(),
                  isClean());
          eventUuid_ = null;
        }
        return eventUuidBuilder_;
      }
      
      // required .Priority new_priority = 2;
      private waldo_protobuffs.UtilProto.Priority newPriority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.Priority, waldo_protobuffs.UtilProto.Priority.Builder, waldo_protobuffs.UtilProto.PriorityOrBuilder> newPriorityBuilder_;
      public boolean hasNewPriority() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public waldo_protobuffs.UtilProto.Priority getNewPriority() {
        if (newPriorityBuilder_ == null) {
          return newPriority_;
        } else {
          return newPriorityBuilder_.getMessage();
        }
      }
      public Builder setNewPriority(waldo_protobuffs.UtilProto.Priority value) {
        if (newPriorityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          newPriority_ = value;
          onChanged();
        } else {
          newPriorityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setNewPriority(
          waldo_protobuffs.UtilProto.Priority.Builder builderForValue) {
        if (newPriorityBuilder_ == null) {
          newPriority_ = builderForValue.build();
          onChanged();
        } else {
          newPriorityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeNewPriority(waldo_protobuffs.UtilProto.Priority value) {
        if (newPriorityBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              newPriority_ != waldo_protobuffs.UtilProto.Priority.getDefaultInstance()) {
            newPriority_ =
              waldo_protobuffs.UtilProto.Priority.newBuilder(newPriority_).mergeFrom(value).buildPartial();
          } else {
            newPriority_ = value;
          }
          onChanged();
        } else {
          newPriorityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearNewPriority() {
        if (newPriorityBuilder_ == null) {
          newPriority_ = waldo_protobuffs.UtilProto.Priority.getDefaultInstance();
          onChanged();
        } else {
          newPriorityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public waldo_protobuffs.UtilProto.Priority.Builder getNewPriorityBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getNewPriorityFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.UtilProto.PriorityOrBuilder getNewPriorityOrBuilder() {
        if (newPriorityBuilder_ != null) {
          return newPriorityBuilder_.getMessageOrBuilder();
        } else {
          return newPriority_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.UtilProto.Priority, waldo_protobuffs.UtilProto.Priority.Builder, waldo_protobuffs.UtilProto.PriorityOrBuilder> 
          getNewPriorityFieldBuilder() {
        if (newPriorityBuilder_ == null) {
          newPriorityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.UtilProto.Priority, waldo_protobuffs.UtilProto.Priority.Builder, waldo_protobuffs.UtilProto.PriorityOrBuilder>(
                  newPriority_,
                  getParentForChildren(),
                  isClean());
          newPriority_ = null;
        }
        return newPriorityBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Promotion)
    }
    
    static {
      defaultInstance = new Promotion(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Promotion)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Promotion_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Promotion_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026promotionMessage.proto\032\nutil.proto\"G\n\t" +
      "Promotion\022\031\n\nevent_uuid\030\001 \002(\0132\005.UUID\022\037\n\014" +
      "new_priority\030\002 \002(\0132\t.PriorityB\"\n\020waldo_p" +
      "rotobuffsB\016PromotionProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Promotion_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Promotion_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Promotion_descriptor,
              new java.lang.String[] { "EventUuid", "NewPriority", },
              waldo_protobuffs.PromotionProto.Promotion.class,
              waldo_protobuffs.PromotionProto.Promotion.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          waldo_protobuffs.UtilProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
