// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: durabilityPrepare.proto

package ralph_protobuffs;

public final class DurabilityPrepareProto {
  private DurabilityPrepareProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DurabilityPrepareOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .UUID event_uuid = 1;
    /**
     * <code>required .UUID event_uuid = 1;</code>
     */
    boolean hasEventUuid();
    /**
     * <code>required .UUID event_uuid = 1;</code>
     */
    ralph_protobuffs.UtilProto.UUID getEventUuid();
    /**
     * <code>required .UUID event_uuid = 1;</code>
     */
    ralph_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder();

    // repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    java.util.List<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID> 
        getRpcArgsList();
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID getRpcArgs(int index);
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    int getRpcArgsCount();
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    java.util.List<? extends ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder> 
        getRpcArgsOrBuilderList();
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder getRpcArgsOrBuilder(
        int index);

    // repeated .UUID endpoints_created = 3;
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    java.util.List<ralph_protobuffs.UtilProto.UUID> 
        getEndpointsCreatedList();
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    ralph_protobuffs.UtilProto.UUID getEndpointsCreated(int index);
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    int getEndpointsCreatedCount();
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    java.util.List<? extends ralph_protobuffs.UtilProto.UUIDOrBuilder> 
        getEndpointsCreatedOrBuilderList();
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    ralph_protobuffs.UtilProto.UUIDOrBuilder getEndpointsCreatedOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DurabilityPrepare}
   */
  public static final class DurabilityPrepare extends
      com.google.protobuf.GeneratedMessage
      implements DurabilityPrepareOrBuilder {
    // Use DurabilityPrepare.newBuilder() to construct.
    private DurabilityPrepare(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DurabilityPrepare(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DurabilityPrepare defaultInstance;
    public static DurabilityPrepare getDefaultInstance() {
      return defaultInstance;
    }

    public DurabilityPrepare getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DurabilityPrepare(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ralph_protobuffs.UtilProto.UUID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = eventUuid_.toBuilder();
              }
              eventUuid_ = input.readMessage(ralph_protobuffs.UtilProto.UUID.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(eventUuid_);
                eventUuid_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rpcArgs_ = new java.util.ArrayList<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID>();
                mutable_bitField0_ |= 0x00000002;
              }
              rpcArgs_.add(input.readMessage(ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                endpointsCreated_ = new java.util.ArrayList<ralph_protobuffs.UtilProto.UUID>();
                mutable_bitField0_ |= 0x00000004;
              }
              endpointsCreated_.add(input.readMessage(ralph_protobuffs.UtilProto.UUID.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rpcArgs_ = java.util.Collections.unmodifiableList(rpcArgs_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          endpointsCreated_ = java.util.Collections.unmodifiableList(endpointsCreated_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.class, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.Builder.class);
    }

    public static com.google.protobuf.Parser<DurabilityPrepare> PARSER =
        new com.google.protobuf.AbstractParser<DurabilityPrepare>() {
      public DurabilityPrepare parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DurabilityPrepare(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DurabilityPrepare> getParserForType() {
      return PARSER;
    }

    public interface PairedPartnerRequestSequenceEndpointUUIDOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required .PartnerRequestSequenceBlock rpc_args = 1;
      /**
       * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
       */
      boolean hasRpcArgs();
      /**
       * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
       */
      ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock getRpcArgs();
      /**
       * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
       */
      ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder getRpcArgsOrBuilder();

      // required .UUID endpoint_uuid = 2;
      /**
       * <code>required .UUID endpoint_uuid = 2;</code>
       */
      boolean hasEndpointUuid();
      /**
       * <code>required .UUID endpoint_uuid = 2;</code>
       */
      ralph_protobuffs.UtilProto.UUID getEndpointUuid();
      /**
       * <code>required .UUID endpoint_uuid = 2;</code>
       */
      ralph_protobuffs.UtilProto.UUIDOrBuilder getEndpointUuidOrBuilder();
    }
    /**
     * Protobuf type {@code DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID}
     */
    public static final class PairedPartnerRequestSequenceEndpointUUID extends
        com.google.protobuf.GeneratedMessage
        implements PairedPartnerRequestSequenceEndpointUUIDOrBuilder {
      // Use PairedPartnerRequestSequenceEndpointUUID.newBuilder() to construct.
      private PairedPartnerRequestSequenceEndpointUUID(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private PairedPartnerRequestSequenceEndpointUUID(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final PairedPartnerRequestSequenceEndpointUUID defaultInstance;
      public static PairedPartnerRequestSequenceEndpointUUID getDefaultInstance() {
        return defaultInstance;
      }

      public PairedPartnerRequestSequenceEndpointUUID getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private PairedPartnerRequestSequenceEndpointUUID(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = rpcArgs_.toBuilder();
                }
                rpcArgs_ = input.readMessage(ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(rpcArgs_);
                  rpcArgs_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 18: {
                ralph_protobuffs.UtilProto.UUID.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = endpointUuid_.toBuilder();
                }
                endpointUuid_ = input.readMessage(ralph_protobuffs.UtilProto.UUID.PARSER, extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(endpointUuid_);
                  endpointUuid_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.class, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder.class);
      }

      public static com.google.protobuf.Parser<PairedPartnerRequestSequenceEndpointUUID> PARSER =
          new com.google.protobuf.AbstractParser<PairedPartnerRequestSequenceEndpointUUID>() {
        public PairedPartnerRequestSequenceEndpointUUID parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PairedPartnerRequestSequenceEndpointUUID(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PairedPartnerRequestSequenceEndpointUUID> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required .PartnerRequestSequenceBlock rpc_args = 1;
      public static final int RPC_ARGS_FIELD_NUMBER = 1;
      private ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock rpcArgs_;
      /**
       * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
       */
      public boolean hasRpcArgs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
       */
      public ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock getRpcArgs() {
        return rpcArgs_;
      }
      /**
       * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
       */
      public ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder getRpcArgsOrBuilder() {
        return rpcArgs_;
      }

      // required .UUID endpoint_uuid = 2;
      public static final int ENDPOINT_UUID_FIELD_NUMBER = 2;
      private ralph_protobuffs.UtilProto.UUID endpointUuid_;
      /**
       * <code>required .UUID endpoint_uuid = 2;</code>
       */
      public boolean hasEndpointUuid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .UUID endpoint_uuid = 2;</code>
       */
      public ralph_protobuffs.UtilProto.UUID getEndpointUuid() {
        return endpointUuid_;
      }
      /**
       * <code>required .UUID endpoint_uuid = 2;</code>
       */
      public ralph_protobuffs.UtilProto.UUIDOrBuilder getEndpointUuidOrBuilder() {
        return endpointUuid_;
      }

      private void initFields() {
        rpcArgs_ = ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
        endpointUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasRpcArgs()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasEndpointUuid()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getRpcArgs().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getEndpointUuid().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, rpcArgs_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, endpointUuid_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, rpcArgs_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, endpointUuid_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.class, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder.class);
        }

        // Construct using ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getRpcArgsFieldBuilder();
            getEndpointUuidFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          if (rpcArgsBuilder_ == null) {
            rpcArgs_ = ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
          } else {
            rpcArgsBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          if (endpointUuidBuilder_ == null) {
            endpointUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
          } else {
            endpointUuidBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_descriptor;
        }

        public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID getDefaultInstanceForType() {
          return ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.getDefaultInstance();
        }

        public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID build() {
          ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID buildPartial() {
          ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID result = new ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (rpcArgsBuilder_ == null) {
            result.rpcArgs_ = rpcArgs_;
          } else {
            result.rpcArgs_ = rpcArgsBuilder_.build();
          }
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (endpointUuidBuilder_ == null) {
            result.endpointUuid_ = endpointUuid_;
          } else {
            result.endpointUuid_ = endpointUuidBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID) {
            return mergeFrom((ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID other) {
          if (other == ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.getDefaultInstance()) return this;
          if (other.hasRpcArgs()) {
            mergeRpcArgs(other.getRpcArgs());
          }
          if (other.hasEndpointUuid()) {
            mergeEndpointUuid(other.getEndpointUuid());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRpcArgs()) {
            
            return false;
          }
          if (!hasEndpointUuid()) {
            
            return false;
          }
          if (!getRpcArgs().isInitialized()) {
            
            return false;
          }
          if (!getEndpointUuid().isInitialized()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required .PartnerRequestSequenceBlock rpc_args = 1;
        private ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock rpcArgs_ = ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock, ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder, ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder> rpcArgsBuilder_;
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public boolean hasRpcArgs() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock getRpcArgs() {
          if (rpcArgsBuilder_ == null) {
            return rpcArgs_;
          } else {
            return rpcArgsBuilder_.getMessage();
          }
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public Builder setRpcArgs(ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock value) {
          if (rpcArgsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            rpcArgs_ = value;
            onChanged();
          } else {
            rpcArgsBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public Builder setRpcArgs(
            ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder builderForValue) {
          if (rpcArgsBuilder_ == null) {
            rpcArgs_ = builderForValue.build();
            onChanged();
          } else {
            rpcArgsBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public Builder mergeRpcArgs(ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock value) {
          if (rpcArgsBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                rpcArgs_ != ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance()) {
              rpcArgs_ =
                ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.newBuilder(rpcArgs_).mergeFrom(value).buildPartial();
            } else {
              rpcArgs_ = value;
            }
            onChanged();
          } else {
            rpcArgsBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public Builder clearRpcArgs() {
          if (rpcArgsBuilder_ == null) {
            rpcArgs_ = ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
            onChanged();
          } else {
            rpcArgsBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder getRpcArgsBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getRpcArgsFieldBuilder().getBuilder();
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        public ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder getRpcArgsOrBuilder() {
          if (rpcArgsBuilder_ != null) {
            return rpcArgsBuilder_.getMessageOrBuilder();
          } else {
            return rpcArgs_;
          }
        }
        /**
         * <code>required .PartnerRequestSequenceBlock rpc_args = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock, ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder, ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder> 
            getRpcArgsFieldBuilder() {
          if (rpcArgsBuilder_ == null) {
            rpcArgsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock, ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder, ralph_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder>(
                    rpcArgs_,
                    getParentForChildren(),
                    isClean());
            rpcArgs_ = null;
          }
          return rpcArgsBuilder_;
        }

        // required .UUID endpoint_uuid = 2;
        private ralph_protobuffs.UtilProto.UUID endpointUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder> endpointUuidBuilder_;
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public boolean hasEndpointUuid() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public ralph_protobuffs.UtilProto.UUID getEndpointUuid() {
          if (endpointUuidBuilder_ == null) {
            return endpointUuid_;
          } else {
            return endpointUuidBuilder_.getMessage();
          }
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public Builder setEndpointUuid(ralph_protobuffs.UtilProto.UUID value) {
          if (endpointUuidBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            endpointUuid_ = value;
            onChanged();
          } else {
            endpointUuidBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public Builder setEndpointUuid(
            ralph_protobuffs.UtilProto.UUID.Builder builderForValue) {
          if (endpointUuidBuilder_ == null) {
            endpointUuid_ = builderForValue.build();
            onChanged();
          } else {
            endpointUuidBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public Builder mergeEndpointUuid(ralph_protobuffs.UtilProto.UUID value) {
          if (endpointUuidBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                endpointUuid_ != ralph_protobuffs.UtilProto.UUID.getDefaultInstance()) {
              endpointUuid_ =
                ralph_protobuffs.UtilProto.UUID.newBuilder(endpointUuid_).mergeFrom(value).buildPartial();
            } else {
              endpointUuid_ = value;
            }
            onChanged();
          } else {
            endpointUuidBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public Builder clearEndpointUuid() {
          if (endpointUuidBuilder_ == null) {
            endpointUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
            onChanged();
          } else {
            endpointUuidBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public ralph_protobuffs.UtilProto.UUID.Builder getEndpointUuidBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getEndpointUuidFieldBuilder().getBuilder();
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        public ralph_protobuffs.UtilProto.UUIDOrBuilder getEndpointUuidOrBuilder() {
          if (endpointUuidBuilder_ != null) {
            return endpointUuidBuilder_.getMessageOrBuilder();
          } else {
            return endpointUuid_;
          }
        }
        /**
         * <code>required .UUID endpoint_uuid = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilder<
            ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder> 
            getEndpointUuidFieldBuilder() {
          if (endpointUuidBuilder_ == null) {
            endpointUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder>(
                    endpointUuid_,
                    getParentForChildren(),
                    isClean());
            endpointUuid_ = null;
          }
          return endpointUuidBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID)
      }

      static {
        defaultInstance = new PairedPartnerRequestSequenceEndpointUUID(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID)
    }

    private int bitField0_;
    // required .UUID event_uuid = 1;
    public static final int EVENT_UUID_FIELD_NUMBER = 1;
    private ralph_protobuffs.UtilProto.UUID eventUuid_;
    /**
     * <code>required .UUID event_uuid = 1;</code>
     */
    public boolean hasEventUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .UUID event_uuid = 1;</code>
     */
    public ralph_protobuffs.UtilProto.UUID getEventUuid() {
      return eventUuid_;
    }
    /**
     * <code>required .UUID event_uuid = 1;</code>
     */
    public ralph_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
      return eventUuid_;
    }

    // repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;
    public static final int RPC_ARGS_FIELD_NUMBER = 2;
    private java.util.List<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID> rpcArgs_;
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    public java.util.List<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID> getRpcArgsList() {
      return rpcArgs_;
    }
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    public java.util.List<? extends ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder> 
        getRpcArgsOrBuilderList() {
      return rpcArgs_;
    }
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    public int getRpcArgsCount() {
      return rpcArgs_.size();
    }
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID getRpcArgs(int index) {
      return rpcArgs_.get(index);
    }
    /**
     * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
     */
    public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder getRpcArgsOrBuilder(
        int index) {
      return rpcArgs_.get(index);
    }

    // repeated .UUID endpoints_created = 3;
    public static final int ENDPOINTS_CREATED_FIELD_NUMBER = 3;
    private java.util.List<ralph_protobuffs.UtilProto.UUID> endpointsCreated_;
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    public java.util.List<ralph_protobuffs.UtilProto.UUID> getEndpointsCreatedList() {
      return endpointsCreated_;
    }
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    public java.util.List<? extends ralph_protobuffs.UtilProto.UUIDOrBuilder> 
        getEndpointsCreatedOrBuilderList() {
      return endpointsCreated_;
    }
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    public int getEndpointsCreatedCount() {
      return endpointsCreated_.size();
    }
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    public ralph_protobuffs.UtilProto.UUID getEndpointsCreated(int index) {
      return endpointsCreated_.get(index);
    }
    /**
     * <code>repeated .UUID endpoints_created = 3;</code>
     *
     * <pre>
     **
     *When we replay, whenever we generate a new endpoint, we should
     *assign them uuids in this order.
     * </pre>
     */
    public ralph_protobuffs.UtilProto.UUIDOrBuilder getEndpointsCreatedOrBuilder(
        int index) {
      return endpointsCreated_.get(index);
    }

    private void initFields() {
      eventUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
      rpcArgs_ = java.util.Collections.emptyList();
      endpointsCreated_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasEventUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getEventUuid().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getRpcArgsCount(); i++) {
        if (!getRpcArgs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getEndpointsCreatedCount(); i++) {
        if (!getEndpointsCreated(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, eventUuid_);
      }
      for (int i = 0; i < rpcArgs_.size(); i++) {
        output.writeMessage(2, rpcArgs_.get(i));
      }
      for (int i = 0; i < endpointsCreated_.size(); i++) {
        output.writeMessage(3, endpointsCreated_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, eventUuid_);
      }
      for (int i = 0; i < rpcArgs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, rpcArgs_.get(i));
      }
      for (int i = 0; i < endpointsCreated_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, endpointsCreated_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DurabilityPrepare}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepareOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.class, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.Builder.class);
      }

      // Construct using ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventUuidFieldBuilder();
          getRpcArgsFieldBuilder();
          getEndpointsCreatedFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (eventUuidBuilder_ == null) {
          eventUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rpcArgsBuilder_ == null) {
          rpcArgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rpcArgsBuilder_.clear();
        }
        if (endpointsCreatedBuilder_ == null) {
          endpointsCreated_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          endpointsCreatedBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ralph_protobuffs.DurabilityPrepareProto.internal_static_DurabilityPrepare_descriptor;
      }

      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare getDefaultInstanceForType() {
        return ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.getDefaultInstance();
      }

      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare build() {
        ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare buildPartial() {
        ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare result = new ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (eventUuidBuilder_ == null) {
          result.eventUuid_ = eventUuid_;
        } else {
          result.eventUuid_ = eventUuidBuilder_.build();
        }
        if (rpcArgsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            rpcArgs_ = java.util.Collections.unmodifiableList(rpcArgs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.rpcArgs_ = rpcArgs_;
        } else {
          result.rpcArgs_ = rpcArgsBuilder_.build();
        }
        if (endpointsCreatedBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            endpointsCreated_ = java.util.Collections.unmodifiableList(endpointsCreated_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.endpointsCreated_ = endpointsCreated_;
        } else {
          result.endpointsCreated_ = endpointsCreatedBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare) {
          return mergeFrom((ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare other) {
        if (other == ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.getDefaultInstance()) return this;
        if (other.hasEventUuid()) {
          mergeEventUuid(other.getEventUuid());
        }
        if (rpcArgsBuilder_ == null) {
          if (!other.rpcArgs_.isEmpty()) {
            if (rpcArgs_.isEmpty()) {
              rpcArgs_ = other.rpcArgs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRpcArgsIsMutable();
              rpcArgs_.addAll(other.rpcArgs_);
            }
            onChanged();
          }
        } else {
          if (!other.rpcArgs_.isEmpty()) {
            if (rpcArgsBuilder_.isEmpty()) {
              rpcArgsBuilder_.dispose();
              rpcArgsBuilder_ = null;
              rpcArgs_ = other.rpcArgs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rpcArgsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRpcArgsFieldBuilder() : null;
            } else {
              rpcArgsBuilder_.addAllMessages(other.rpcArgs_);
            }
          }
        }
        if (endpointsCreatedBuilder_ == null) {
          if (!other.endpointsCreated_.isEmpty()) {
            if (endpointsCreated_.isEmpty()) {
              endpointsCreated_ = other.endpointsCreated_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureEndpointsCreatedIsMutable();
              endpointsCreated_.addAll(other.endpointsCreated_);
            }
            onChanged();
          }
        } else {
          if (!other.endpointsCreated_.isEmpty()) {
            if (endpointsCreatedBuilder_.isEmpty()) {
              endpointsCreatedBuilder_.dispose();
              endpointsCreatedBuilder_ = null;
              endpointsCreated_ = other.endpointsCreated_;
              bitField0_ = (bitField0_ & ~0x00000004);
              endpointsCreatedBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEndpointsCreatedFieldBuilder() : null;
            } else {
              endpointsCreatedBuilder_.addAllMessages(other.endpointsCreated_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEventUuid()) {
          
          return false;
        }
        if (!getEventUuid().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getRpcArgsCount(); i++) {
          if (!getRpcArgs(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getEndpointsCreatedCount(); i++) {
          if (!getEndpointsCreated(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .UUID event_uuid = 1;
      private ralph_protobuffs.UtilProto.UUID eventUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder> eventUuidBuilder_;
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public boolean hasEventUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public ralph_protobuffs.UtilProto.UUID getEventUuid() {
        if (eventUuidBuilder_ == null) {
          return eventUuid_;
        } else {
          return eventUuidBuilder_.getMessage();
        }
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public Builder setEventUuid(ralph_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventUuid_ = value;
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public Builder setEventUuid(
          ralph_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = builderForValue.build();
          onChanged();
        } else {
          eventUuidBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public Builder mergeEventUuid(ralph_protobuffs.UtilProto.UUID value) {
        if (eventUuidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              eventUuid_ != ralph_protobuffs.UtilProto.UUID.getDefaultInstance()) {
            eventUuid_ =
              ralph_protobuffs.UtilProto.UUID.newBuilder(eventUuid_).mergeFrom(value).buildPartial();
          } else {
            eventUuid_ = value;
          }
          onChanged();
        } else {
          eventUuidBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public Builder clearEventUuid() {
        if (eventUuidBuilder_ == null) {
          eventUuid_ = ralph_protobuffs.UtilProto.UUID.getDefaultInstance();
          onChanged();
        } else {
          eventUuidBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public ralph_protobuffs.UtilProto.UUID.Builder getEventUuidBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getEventUuidFieldBuilder().getBuilder();
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      public ralph_protobuffs.UtilProto.UUIDOrBuilder getEventUuidOrBuilder() {
        if (eventUuidBuilder_ != null) {
          return eventUuidBuilder_.getMessageOrBuilder();
        } else {
          return eventUuid_;
        }
      }
      /**
       * <code>required .UUID event_uuid = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder> 
          getEventUuidFieldBuilder() {
        if (eventUuidBuilder_ == null) {
          eventUuidBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder>(
                  eventUuid_,
                  getParentForChildren(),
                  isClean());
          eventUuid_ = null;
        }
        return eventUuidBuilder_;
      }

      // repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;
      private java.util.List<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID> rpcArgs_ =
        java.util.Collections.emptyList();
      private void ensureRpcArgsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rpcArgs_ = new java.util.ArrayList<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID>(rpcArgs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder> rpcArgsBuilder_;

      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public java.util.List<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID> getRpcArgsList() {
        if (rpcArgsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rpcArgs_);
        } else {
          return rpcArgsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public int getRpcArgsCount() {
        if (rpcArgsBuilder_ == null) {
          return rpcArgs_.size();
        } else {
          return rpcArgsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID getRpcArgs(int index) {
        if (rpcArgsBuilder_ == null) {
          return rpcArgs_.get(index);
        } else {
          return rpcArgsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder setRpcArgs(
          int index, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID value) {
        if (rpcArgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRpcArgsIsMutable();
          rpcArgs_.set(index, value);
          onChanged();
        } else {
          rpcArgsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder setRpcArgs(
          int index, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder builderForValue) {
        if (rpcArgsBuilder_ == null) {
          ensureRpcArgsIsMutable();
          rpcArgs_.set(index, builderForValue.build());
          onChanged();
        } else {
          rpcArgsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder addRpcArgs(ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID value) {
        if (rpcArgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRpcArgsIsMutable();
          rpcArgs_.add(value);
          onChanged();
        } else {
          rpcArgsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder addRpcArgs(
          int index, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID value) {
        if (rpcArgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRpcArgsIsMutable();
          rpcArgs_.add(index, value);
          onChanged();
        } else {
          rpcArgsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder addRpcArgs(
          ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder builderForValue) {
        if (rpcArgsBuilder_ == null) {
          ensureRpcArgsIsMutable();
          rpcArgs_.add(builderForValue.build());
          onChanged();
        } else {
          rpcArgsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder addRpcArgs(
          int index, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder builderForValue) {
        if (rpcArgsBuilder_ == null) {
          ensureRpcArgsIsMutable();
          rpcArgs_.add(index, builderForValue.build());
          onChanged();
        } else {
          rpcArgsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder addAllRpcArgs(
          java.lang.Iterable<? extends ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID> values) {
        if (rpcArgsBuilder_ == null) {
          ensureRpcArgsIsMutable();
          super.addAll(values, rpcArgs_);
          onChanged();
        } else {
          rpcArgsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder clearRpcArgs() {
        if (rpcArgsBuilder_ == null) {
          rpcArgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rpcArgsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public Builder removeRpcArgs(int index) {
        if (rpcArgsBuilder_ == null) {
          ensureRpcArgsIsMutable();
          rpcArgs_.remove(index);
          onChanged();
        } else {
          rpcArgsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder getRpcArgsBuilder(
          int index) {
        return getRpcArgsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder getRpcArgsOrBuilder(
          int index) {
        if (rpcArgsBuilder_ == null) {
          return rpcArgs_.get(index);  } else {
          return rpcArgsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public java.util.List<? extends ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder> 
           getRpcArgsOrBuilderList() {
        if (rpcArgsBuilder_ != null) {
          return rpcArgsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rpcArgs_);
        }
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder addRpcArgsBuilder() {
        return getRpcArgsFieldBuilder().addBuilder(
            ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.getDefaultInstance());
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder addRpcArgsBuilder(
          int index) {
        return getRpcArgsFieldBuilder().addBuilder(
            index, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.getDefaultInstance());
      }
      /**
       * <code>repeated .DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID rpc_args = 2;</code>
       */
      public java.util.List<ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder> 
           getRpcArgsBuilderList() {
        return getRpcArgsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder> 
          getRpcArgsFieldBuilder() {
        if (rpcArgsBuilder_ == null) {
          rpcArgsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUID.Builder, ralph_protobuffs.DurabilityPrepareProto.DurabilityPrepare.PairedPartnerRequestSequenceEndpointUUIDOrBuilder>(
                  rpcArgs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          rpcArgs_ = null;
        }
        return rpcArgsBuilder_;
      }

      // repeated .UUID endpoints_created = 3;
      private java.util.List<ralph_protobuffs.UtilProto.UUID> endpointsCreated_ =
        java.util.Collections.emptyList();
      private void ensureEndpointsCreatedIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          endpointsCreated_ = new java.util.ArrayList<ralph_protobuffs.UtilProto.UUID>(endpointsCreated_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder> endpointsCreatedBuilder_;

      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public java.util.List<ralph_protobuffs.UtilProto.UUID> getEndpointsCreatedList() {
        if (endpointsCreatedBuilder_ == null) {
          return java.util.Collections.unmodifiableList(endpointsCreated_);
        } else {
          return endpointsCreatedBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public int getEndpointsCreatedCount() {
        if (endpointsCreatedBuilder_ == null) {
          return endpointsCreated_.size();
        } else {
          return endpointsCreatedBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public ralph_protobuffs.UtilProto.UUID getEndpointsCreated(int index) {
        if (endpointsCreatedBuilder_ == null) {
          return endpointsCreated_.get(index);
        } else {
          return endpointsCreatedBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder setEndpointsCreated(
          int index, ralph_protobuffs.UtilProto.UUID value) {
        if (endpointsCreatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndpointsCreatedIsMutable();
          endpointsCreated_.set(index, value);
          onChanged();
        } else {
          endpointsCreatedBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder setEndpointsCreated(
          int index, ralph_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (endpointsCreatedBuilder_ == null) {
          ensureEndpointsCreatedIsMutable();
          endpointsCreated_.set(index, builderForValue.build());
          onChanged();
        } else {
          endpointsCreatedBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder addEndpointsCreated(ralph_protobuffs.UtilProto.UUID value) {
        if (endpointsCreatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndpointsCreatedIsMutable();
          endpointsCreated_.add(value);
          onChanged();
        } else {
          endpointsCreatedBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder addEndpointsCreated(
          int index, ralph_protobuffs.UtilProto.UUID value) {
        if (endpointsCreatedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEndpointsCreatedIsMutable();
          endpointsCreated_.add(index, value);
          onChanged();
        } else {
          endpointsCreatedBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder addEndpointsCreated(
          ralph_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (endpointsCreatedBuilder_ == null) {
          ensureEndpointsCreatedIsMutable();
          endpointsCreated_.add(builderForValue.build());
          onChanged();
        } else {
          endpointsCreatedBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder addEndpointsCreated(
          int index, ralph_protobuffs.UtilProto.UUID.Builder builderForValue) {
        if (endpointsCreatedBuilder_ == null) {
          ensureEndpointsCreatedIsMutable();
          endpointsCreated_.add(index, builderForValue.build());
          onChanged();
        } else {
          endpointsCreatedBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder addAllEndpointsCreated(
          java.lang.Iterable<? extends ralph_protobuffs.UtilProto.UUID> values) {
        if (endpointsCreatedBuilder_ == null) {
          ensureEndpointsCreatedIsMutable();
          super.addAll(values, endpointsCreated_);
          onChanged();
        } else {
          endpointsCreatedBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder clearEndpointsCreated() {
        if (endpointsCreatedBuilder_ == null) {
          endpointsCreated_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          endpointsCreatedBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public Builder removeEndpointsCreated(int index) {
        if (endpointsCreatedBuilder_ == null) {
          ensureEndpointsCreatedIsMutable();
          endpointsCreated_.remove(index);
          onChanged();
        } else {
          endpointsCreatedBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public ralph_protobuffs.UtilProto.UUID.Builder getEndpointsCreatedBuilder(
          int index) {
        return getEndpointsCreatedFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public ralph_protobuffs.UtilProto.UUIDOrBuilder getEndpointsCreatedOrBuilder(
          int index) {
        if (endpointsCreatedBuilder_ == null) {
          return endpointsCreated_.get(index);  } else {
          return endpointsCreatedBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public java.util.List<? extends ralph_protobuffs.UtilProto.UUIDOrBuilder> 
           getEndpointsCreatedOrBuilderList() {
        if (endpointsCreatedBuilder_ != null) {
          return endpointsCreatedBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(endpointsCreated_);
        }
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public ralph_protobuffs.UtilProto.UUID.Builder addEndpointsCreatedBuilder() {
        return getEndpointsCreatedFieldBuilder().addBuilder(
            ralph_protobuffs.UtilProto.UUID.getDefaultInstance());
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public ralph_protobuffs.UtilProto.UUID.Builder addEndpointsCreatedBuilder(
          int index) {
        return getEndpointsCreatedFieldBuilder().addBuilder(
            index, ralph_protobuffs.UtilProto.UUID.getDefaultInstance());
      }
      /**
       * <code>repeated .UUID endpoints_created = 3;</code>
       *
       * <pre>
       **
       *When we replay, whenever we generate a new endpoint, we should
       *assign them uuids in this order.
       * </pre>
       */
      public java.util.List<ralph_protobuffs.UtilProto.UUID.Builder> 
           getEndpointsCreatedBuilderList() {
        return getEndpointsCreatedFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder> 
          getEndpointsCreatedFieldBuilder() {
        if (endpointsCreatedBuilder_ == null) {
          endpointsCreatedBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ralph_protobuffs.UtilProto.UUID, ralph_protobuffs.UtilProto.UUID.Builder, ralph_protobuffs.UtilProto.UUIDOrBuilder>(
                  endpointsCreated_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          endpointsCreated_ = null;
        }
        return endpointsCreatedBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DurabilityPrepare)
    }

    static {
      defaultInstance = new DurabilityPrepare(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DurabilityPrepare)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DurabilityPrepare_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DurabilityPrepare_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027durabilityPrepare.proto\032\nutil.proto\032!p" +
      "artnerRequestSequenceBlock.proto\"\231\002\n\021Dur" +
      "abilityPrepare\022\031\n\nevent_uuid\030\001 \002(\0132\005.UUI" +
      "D\022M\n\010rpc_args\030\002 \003(\0132;.DurabilityPrepare." +
      "PairedPartnerRequestSequenceEndpointUUID" +
      "\022 \n\021endpoints_created\030\003 \003(\0132\005.UUID\032x\n(Pa" +
      "iredPartnerRequestSequenceEndpointUUID\022." +
      "\n\010rpc_args\030\001 \002(\0132\034.PartnerRequestSequenc" +
      "eBlock\022\034\n\rendpoint_uuid\030\002 \002(\0132\005.UUIDB*\n\020" +
      "ralph_protobuffsB\026DurabilityPrepareProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_DurabilityPrepare_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_DurabilityPrepare_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DurabilityPrepare_descriptor,
              new java.lang.String[] { "EventUuid", "RpcArgs", "EndpointsCreated", });
          internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_descriptor =
            internal_static_DurabilityPrepare_descriptor.getNestedTypes().get(0);
          internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_DurabilityPrepare_PairedPartnerRequestSequenceEndpointUUID_descriptor,
              new java.lang.String[] { "RpcArgs", "EndpointUuid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ralph_protobuffs.UtilProto.getDescriptor(),
          ralph_protobuffs.PartnerRequestSequenceBlockProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
