// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: singleDeviceUpdateList.proto

package ralph_version_protobuffs;

public final class SingleDeviceUpdateListProto {
  private SingleDeviceUpdateListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SingleDeviceUpdateListMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string device_id = 1;
    /**
     * <code>required string device_id = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>required string device_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    // repeated .SingleDeviceUpdateMessage update_list = 2;
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    java.util.List<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage> 
        getUpdateListList();
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage getUpdateList(int index);
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    int getUpdateListCount();
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    java.util.List<? extends ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder> 
        getUpdateListOrBuilderList();
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder getUpdateListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code SingleDeviceUpdateListMessage}
   */
  public static final class SingleDeviceUpdateListMessage extends
      com.google.protobuf.GeneratedMessage
      implements SingleDeviceUpdateListMessageOrBuilder {
    // Use SingleDeviceUpdateListMessage.newBuilder() to construct.
    private SingleDeviceUpdateListMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SingleDeviceUpdateListMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SingleDeviceUpdateListMessage defaultInstance;
    public static SingleDeviceUpdateListMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SingleDeviceUpdateListMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SingleDeviceUpdateListMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                updateList_ = new java.util.ArrayList<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              updateList_.add(input.readMessage(ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          updateList_ = java.util.Collections.unmodifiableList(updateList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ralph_version_protobuffs.SingleDeviceUpdateListProto.internal_static_SingleDeviceUpdateListMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ralph_version_protobuffs.SingleDeviceUpdateListProto.internal_static_SingleDeviceUpdateListMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.class, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SingleDeviceUpdateListMessage> PARSER =
        new com.google.protobuf.AbstractParser<SingleDeviceUpdateListMessage>() {
      public SingleDeviceUpdateListMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SingleDeviceUpdateListMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SingleDeviceUpdateListMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string device_id = 1;
    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    /**
     * <code>required string device_id = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string device_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .SingleDeviceUpdateMessage update_list = 2;
    public static final int UPDATE_LIST_FIELD_NUMBER = 2;
    private java.util.List<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage> updateList_;
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    public java.util.List<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage> getUpdateListList() {
      return updateList_;
    }
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    public java.util.List<? extends ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder> 
        getUpdateListOrBuilderList() {
      return updateList_;
    }
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    public int getUpdateListCount() {
      return updateList_.size();
    }
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    public ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage getUpdateList(int index) {
      return updateList_.get(index);
    }
    /**
     * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
     */
    public ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder getUpdateListOrBuilder(
        int index) {
      return updateList_.get(index);
    }

    private void initFields() {
      deviceId_ = "";
      updateList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getUpdateListCount(); i++) {
        if (!getUpdateList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      for (int i = 0; i < updateList_.size(); i++) {
        output.writeMessage(2, updateList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      for (int i = 0; i < updateList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, updateList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SingleDeviceUpdateListMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ralph_version_protobuffs.SingleDeviceUpdateListProto.internal_static_SingleDeviceUpdateListMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ralph_version_protobuffs.SingleDeviceUpdateListProto.internal_static_SingleDeviceUpdateListMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.class, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder.class);
      }

      // Construct using ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUpdateListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (updateListBuilder_ == null) {
          updateList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          updateListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ralph_version_protobuffs.SingleDeviceUpdateListProto.internal_static_SingleDeviceUpdateListMessage_descriptor;
      }

      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage getDefaultInstanceForType() {
        return ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.getDefaultInstance();
      }

      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage build() {
        ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage buildPartial() {
        ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage result = new ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (updateListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            updateList_ = java.util.Collections.unmodifiableList(updateList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.updateList_ = updateList_;
        } else {
          result.updateList_ = updateListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage) {
          return mergeFrom((ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage other) {
        if (other == ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          bitField0_ |= 0x00000001;
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (updateListBuilder_ == null) {
          if (!other.updateList_.isEmpty()) {
            if (updateList_.isEmpty()) {
              updateList_ = other.updateList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureUpdateListIsMutable();
              updateList_.addAll(other.updateList_);
            }
            onChanged();
          }
        } else {
          if (!other.updateList_.isEmpty()) {
            if (updateListBuilder_.isEmpty()) {
              updateListBuilder_.dispose();
              updateListBuilder_ = null;
              updateList_ = other.updateList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              updateListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUpdateListFieldBuilder() : null;
            } else {
              updateListBuilder_.addAllMessages(other.updateList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        for (int i = 0; i < getUpdateListCount(); i++) {
          if (!getUpdateList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string device_id = 1;
      private java.lang.Object deviceId_ = "";
      /**
       * <code>required string device_id = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>required string device_id = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }

      // repeated .SingleDeviceUpdateMessage update_list = 2;
      private java.util.List<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage> updateList_ =
        java.util.Collections.emptyList();
      private void ensureUpdateListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          updateList_ = new java.util.ArrayList<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage>(updateList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder> updateListBuilder_;

      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public java.util.List<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage> getUpdateListList() {
        if (updateListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(updateList_);
        } else {
          return updateListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public int getUpdateListCount() {
        if (updateListBuilder_ == null) {
          return updateList_.size();
        } else {
          return updateListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage getUpdateList(int index) {
        if (updateListBuilder_ == null) {
          return updateList_.get(index);
        } else {
          return updateListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder setUpdateList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage value) {
        if (updateListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateListIsMutable();
          updateList_.set(index, value);
          onChanged();
        } else {
          updateListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder setUpdateList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder builderForValue) {
        if (updateListBuilder_ == null) {
          ensureUpdateListIsMutable();
          updateList_.set(index, builderForValue.build());
          onChanged();
        } else {
          updateListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder addUpdateList(ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage value) {
        if (updateListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateListIsMutable();
          updateList_.add(value);
          onChanged();
        } else {
          updateListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder addUpdateList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage value) {
        if (updateListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUpdateListIsMutable();
          updateList_.add(index, value);
          onChanged();
        } else {
          updateListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder addUpdateList(
          ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder builderForValue) {
        if (updateListBuilder_ == null) {
          ensureUpdateListIsMutable();
          updateList_.add(builderForValue.build());
          onChanged();
        } else {
          updateListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder addUpdateList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder builderForValue) {
        if (updateListBuilder_ == null) {
          ensureUpdateListIsMutable();
          updateList_.add(index, builderForValue.build());
          onChanged();
        } else {
          updateListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder addAllUpdateList(
          java.lang.Iterable<? extends ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage> values) {
        if (updateListBuilder_ == null) {
          ensureUpdateListIsMutable();
          super.addAll(values, updateList_);
          onChanged();
        } else {
          updateListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder clearUpdateList() {
        if (updateListBuilder_ == null) {
          updateList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          updateListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public Builder removeUpdateList(int index) {
        if (updateListBuilder_ == null) {
          ensureUpdateListIsMutable();
          updateList_.remove(index);
          onChanged();
        } else {
          updateListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder getUpdateListBuilder(
          int index) {
        return getUpdateListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder getUpdateListOrBuilder(
          int index) {
        if (updateListBuilder_ == null) {
          return updateList_.get(index);  } else {
          return updateListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public java.util.List<? extends ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder> 
           getUpdateListOrBuilderList() {
        if (updateListBuilder_ != null) {
          return updateListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(updateList_);
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder addUpdateListBuilder() {
        return getUpdateListFieldBuilder().addBuilder(
            ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder addUpdateListBuilder(
          int index) {
        return getUpdateListFieldBuilder().addBuilder(
            index, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleDeviceUpdateMessage update_list = 2;</code>
       */
      public java.util.List<ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder> 
           getUpdateListBuilderList() {
        return getUpdateListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder> 
          getUpdateListFieldBuilder() {
        if (updateListBuilder_ == null) {
          updateListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessage.Builder, ralph_version_protobuffs.SingleDeviceUpdateProto.SingleDeviceUpdateMessageOrBuilder>(
                  updateList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          updateList_ = null;
        }
        return updateListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SingleDeviceUpdateListMessage)
    }

    static {
      defaultInstance = new SingleDeviceUpdateListMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SingleDeviceUpdateListMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SingleDeviceUpdateListMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SingleDeviceUpdateListMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034singleDeviceUpdateList.proto\032\030singleDe" +
      "viceUpdate.proto\"c\n\035SingleDeviceUpdateLi" +
      "stMessage\022\021\n\tdevice_id\030\001 \002(\t\022/\n\013update_l" +
      "ist\030\002 \003(\0132\032.SingleDeviceUpdateMessageB7\n" +
      "\030ralph_version_protobuffsB\033SingleDeviceU" +
      "pdateListProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SingleDeviceUpdateListMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SingleDeviceUpdateListMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SingleDeviceUpdateListMessage_descriptor,
              new java.lang.String[] { "DeviceId", "UpdateList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ralph_version_protobuffs.SingleDeviceUpdateProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
