// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: versionResponse.proto

package ralph_version_protobuffs;

public final class VersionResponseProto {
  private VersionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VersionResponseMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint64 query_id = 1;
    /**
     * <code>required uint64 query_id = 1;</code>
     *
     * <pre>
     * identifier so that other side knows which query this is a
     * response to.
     * </pre>
     */
    boolean hasQueryId();
    /**
     * <code>required uint64 query_id = 1;</code>
     *
     * <pre>
     * identifier so that other side knows which query this is a
     * response to.
     * </pre>
     */
    long getQueryId();

    // repeated .SingleDeviceUpdateListMessage device_list = 2;
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    java.util.List<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage> 
        getDeviceListList();
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage getDeviceList(int index);
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    int getDeviceListCount();
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    java.util.List<? extends ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder> 
        getDeviceListOrBuilderList();
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder getDeviceListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code VersionResponseMessage}
   */
  public static final class VersionResponseMessage extends
      com.google.protobuf.GeneratedMessage
      implements VersionResponseMessageOrBuilder {
    // Use VersionResponseMessage.newBuilder() to construct.
    private VersionResponseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VersionResponseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VersionResponseMessage defaultInstance;
    public static VersionResponseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public VersionResponseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VersionResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              queryId_ = input.readUInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                deviceList_ = new java.util.ArrayList<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              deviceList_.add(input.readMessage(ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          deviceList_ = java.util.Collections.unmodifiableList(deviceList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ralph_version_protobuffs.VersionResponseProto.internal_static_VersionResponseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ralph_version_protobuffs.VersionResponseProto.internal_static_VersionResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage.class, ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<VersionResponseMessage> PARSER =
        new com.google.protobuf.AbstractParser<VersionResponseMessage>() {
      public VersionResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VersionResponseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VersionResponseMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint64 query_id = 1;
    public static final int QUERY_ID_FIELD_NUMBER = 1;
    private long queryId_;
    /**
     * <code>required uint64 query_id = 1;</code>
     *
     * <pre>
     * identifier so that other side knows which query this is a
     * response to.
     * </pre>
     */
    public boolean hasQueryId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 query_id = 1;</code>
     *
     * <pre>
     * identifier so that other side knows which query this is a
     * response to.
     * </pre>
     */
    public long getQueryId() {
      return queryId_;
    }

    // repeated .SingleDeviceUpdateListMessage device_list = 2;
    public static final int DEVICE_LIST_FIELD_NUMBER = 2;
    private java.util.List<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage> deviceList_;
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    public java.util.List<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage> getDeviceListList() {
      return deviceList_;
    }
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    public java.util.List<? extends ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder> 
        getDeviceListOrBuilderList() {
      return deviceList_;
    }
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    public int getDeviceListCount() {
      return deviceList_.size();
    }
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage getDeviceList(int index) {
      return deviceList_.get(index);
    }
    /**
     * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
     */
    public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder getDeviceListOrBuilder(
        int index) {
      return deviceList_.get(index);
    }

    private void initFields() {
      queryId_ = 0L;
      deviceList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasQueryId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDeviceListCount(); i++) {
        if (!getDeviceList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, queryId_);
      }
      for (int i = 0; i < deviceList_.size(); i++) {
        output.writeMessage(2, deviceList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, queryId_);
      }
      for (int i = 0; i < deviceList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, deviceList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VersionResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ralph_version_protobuffs.VersionResponseProto.VersionResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ralph_version_protobuffs.VersionResponseProto.internal_static_VersionResponseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ralph_version_protobuffs.VersionResponseProto.internal_static_VersionResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage.class, ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage.Builder.class);
      }

      // Construct using ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        queryId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (deviceListBuilder_ == null) {
          deviceList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          deviceListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ralph_version_protobuffs.VersionResponseProto.internal_static_VersionResponseMessage_descriptor;
      }

      public ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage getDefaultInstanceForType() {
        return ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage.getDefaultInstance();
      }

      public ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage build() {
        ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage buildPartial() {
        ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage result = new ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.queryId_ = queryId_;
        if (deviceListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            deviceList_ = java.util.Collections.unmodifiableList(deviceList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.deviceList_ = deviceList_;
        } else {
          result.deviceList_ = deviceListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage) {
          return mergeFrom((ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage other) {
        if (other == ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage.getDefaultInstance()) return this;
        if (other.hasQueryId()) {
          setQueryId(other.getQueryId());
        }
        if (deviceListBuilder_ == null) {
          if (!other.deviceList_.isEmpty()) {
            if (deviceList_.isEmpty()) {
              deviceList_ = other.deviceList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDeviceListIsMutable();
              deviceList_.addAll(other.deviceList_);
            }
            onChanged();
          }
        } else {
          if (!other.deviceList_.isEmpty()) {
            if (deviceListBuilder_.isEmpty()) {
              deviceListBuilder_.dispose();
              deviceListBuilder_ = null;
              deviceList_ = other.deviceList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              deviceListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDeviceListFieldBuilder() : null;
            } else {
              deviceListBuilder_.addAllMessages(other.deviceList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasQueryId()) {
          
          return false;
        }
        for (int i = 0; i < getDeviceListCount(); i++) {
          if (!getDeviceList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ralph_version_protobuffs.VersionResponseProto.VersionResponseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint64 query_id = 1;
      private long queryId_ ;
      /**
       * <code>required uint64 query_id = 1;</code>
       *
       * <pre>
       * identifier so that other side knows which query this is a
       * response to.
       * </pre>
       */
      public boolean hasQueryId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 query_id = 1;</code>
       *
       * <pre>
       * identifier so that other side knows which query this is a
       * response to.
       * </pre>
       */
      public long getQueryId() {
        return queryId_;
      }
      /**
       * <code>required uint64 query_id = 1;</code>
       *
       * <pre>
       * identifier so that other side knows which query this is a
       * response to.
       * </pre>
       */
      public Builder setQueryId(long value) {
        bitField0_ |= 0x00000001;
        queryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 query_id = 1;</code>
       *
       * <pre>
       * identifier so that other side knows which query this is a
       * response to.
       * </pre>
       */
      public Builder clearQueryId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        queryId_ = 0L;
        onChanged();
        return this;
      }

      // repeated .SingleDeviceUpdateListMessage device_list = 2;
      private java.util.List<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage> deviceList_ =
        java.util.Collections.emptyList();
      private void ensureDeviceListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          deviceList_ = new java.util.ArrayList<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage>(deviceList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder> deviceListBuilder_;

      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public java.util.List<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage> getDeviceListList() {
        if (deviceListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(deviceList_);
        } else {
          return deviceListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public int getDeviceListCount() {
        if (deviceListBuilder_ == null) {
          return deviceList_.size();
        } else {
          return deviceListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage getDeviceList(int index) {
        if (deviceListBuilder_ == null) {
          return deviceList_.get(index);
        } else {
          return deviceListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder setDeviceList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage value) {
        if (deviceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceListIsMutable();
          deviceList_.set(index, value);
          onChanged();
        } else {
          deviceListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder setDeviceList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder builderForValue) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.set(index, builderForValue.build());
          onChanged();
        } else {
          deviceListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder addDeviceList(ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage value) {
        if (deviceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceListIsMutable();
          deviceList_.add(value);
          onChanged();
        } else {
          deviceListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder addDeviceList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage value) {
        if (deviceListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceListIsMutable();
          deviceList_.add(index, value);
          onChanged();
        } else {
          deviceListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder addDeviceList(
          ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder builderForValue) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.add(builderForValue.build());
          onChanged();
        } else {
          deviceListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder addDeviceList(
          int index, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder builderForValue) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.add(index, builderForValue.build());
          onChanged();
        } else {
          deviceListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder addAllDeviceList(
          java.lang.Iterable<? extends ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage> values) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          super.addAll(values, deviceList_);
          onChanged();
        } else {
          deviceListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder clearDeviceList() {
        if (deviceListBuilder_ == null) {
          deviceList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          deviceListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public Builder removeDeviceList(int index) {
        if (deviceListBuilder_ == null) {
          ensureDeviceListIsMutable();
          deviceList_.remove(index);
          onChanged();
        } else {
          deviceListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder getDeviceListBuilder(
          int index) {
        return getDeviceListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder getDeviceListOrBuilder(
          int index) {
        if (deviceListBuilder_ == null) {
          return deviceList_.get(index);  } else {
          return deviceListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public java.util.List<? extends ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder> 
           getDeviceListOrBuilderList() {
        if (deviceListBuilder_ != null) {
          return deviceListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(deviceList_);
        }
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder addDeviceListBuilder() {
        return getDeviceListFieldBuilder().addBuilder(
            ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder addDeviceListBuilder(
          int index) {
        return getDeviceListFieldBuilder().addBuilder(
            index, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleDeviceUpdateListMessage device_list = 2;</code>
       */
      public java.util.List<ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder> 
           getDeviceListBuilderList() {
        return getDeviceListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder> 
          getDeviceListFieldBuilder() {
        if (deviceListBuilder_ == null) {
          deviceListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessage.Builder, ralph_version_protobuffs.SingleDeviceUpdateListProto.SingleDeviceUpdateListMessageOrBuilder>(
                  deviceList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          deviceList_ = null;
        }
        return deviceListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:VersionResponseMessage)
    }

    static {
      defaultInstance = new VersionResponseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VersionResponseMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VersionResponseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VersionResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025versionResponse.proto\032\034singleDeviceUpd" +
      "ateList.proto\"_\n\026VersionResponseMessage\022" +
      "\020\n\010query_id\030\001 \002(\004\0223\n\013device_list\030\002 \003(\0132\036" +
      ".SingleDeviceUpdateListMessageB0\n\030ralph_" +
      "version_protobuffsB\024VersionResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_VersionResponseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_VersionResponseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VersionResponseMessage_descriptor,
              new java.lang.String[] { "QueryId", "DeviceList", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ralph_version_protobuffs.SingleDeviceUpdateListProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
