// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generalMessage.proto

package ralph_protobuffs;

public final class GeneralMessageProto {
  private GeneralMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GeneralMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .PartnerNotifyReady notify_ready = 1;
    boolean hasNotifyReady();
    waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady getNotifyReady();
    waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReadyOrBuilder getNotifyReadyOrBuilder();
    
    // optional .PartnerRequestSequenceBlock request_sequence_block = 2;
    boolean hasRequestSequenceBlock();
    waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock getRequestSequenceBlock();
    waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder getRequestSequenceBlockOrBuilder();
    
    // optional .PartnerFirstPhaseResultMessage first_phase_result = 3;
    boolean hasFirstPhaseResult();
    waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage getFirstPhaseResult();
    waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessageOrBuilder getFirstPhaseResultOrBuilder();
    
    // optional .PartnerBackoutCommitRequest backout_commit_request = 4;
    boolean hasBackoutCommitRequest();
    waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest getBackoutCommitRequest();
    waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequestOrBuilder getBackoutCommitRequestOrBuilder();
    
    // optional .PartnerCompleteCommitRequest complete_commit_request = 5;
    boolean hasCompleteCommitRequest();
    waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest getCompleteCommitRequest();
    waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequestOrBuilder getCompleteCommitRequestOrBuilder();
    
    // optional .PartnerCommitRequest commit_request = 6;
    boolean hasCommitRequest();
    waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest getCommitRequest();
    waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequestOrBuilder getCommitRequestOrBuilder();
    
    // optional .PartnerStop stop = 7;
    boolean hasStop();
    waldo_protobuffs.PartnerStopProto.PartnerStop getStop();
    waldo_protobuffs.PartnerStopProto.PartnerStopOrBuilder getStopOrBuilder();
    
    // optional .PartnerError error = 8;
    boolean hasError();
    waldo_protobuffs.PartnerErrorProto.PartnerError getError();
    waldo_protobuffs.PartnerErrorProto.PartnerErrorOrBuilder getErrorOrBuilder();
    
    // optional .Heartbeat heartbeat = 9;
    boolean hasHeartbeat();
    waldo_protobuffs.HeartbeatProto.Heartbeat getHeartbeat();
    waldo_protobuffs.HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder();
    
    // optional .Promotion promotion = 10;
    boolean hasPromotion();
    waldo_protobuffs.PromotionProto.Promotion getPromotion();
    waldo_protobuffs.PromotionProto.PromotionOrBuilder getPromotionOrBuilder();
    
    // required uint64 timestamp = 11;
    boolean hasTimestamp();
    long getTimestamp();
  }
  public static final class GeneralMessage extends
      com.google.protobuf.GeneratedMessage
      implements GeneralMessageOrBuilder {
    // Use GeneralMessage.newBuilder() to construct.
    private GeneralMessage(Builder builder) {
      super(builder);
    }
    private GeneralMessage(boolean noInit) {}
    
    private static final GeneralMessage defaultInstance;
    public static GeneralMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public GeneralMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ralph_protobuffs.GeneralMessageProto.internal_static_GeneralMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ralph_protobuffs.GeneralMessageProto.internal_static_GeneralMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .PartnerNotifyReady notify_ready = 1;
    public static final int NOTIFY_READY_FIELD_NUMBER = 1;
    private waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady notifyReady_;
    public boolean hasNotifyReady() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady getNotifyReady() {
      return notifyReady_;
    }
    public waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReadyOrBuilder getNotifyReadyOrBuilder() {
      return notifyReady_;
    }
    
    // optional .PartnerRequestSequenceBlock request_sequence_block = 2;
    public static final int REQUEST_SEQUENCE_BLOCK_FIELD_NUMBER = 2;
    private waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock requestSequenceBlock_;
    public boolean hasRequestSequenceBlock() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock getRequestSequenceBlock() {
      return requestSequenceBlock_;
    }
    public waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder getRequestSequenceBlockOrBuilder() {
      return requestSequenceBlock_;
    }
    
    // optional .PartnerFirstPhaseResultMessage first_phase_result = 3;
    public static final int FIRST_PHASE_RESULT_FIELD_NUMBER = 3;
    private waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage firstPhaseResult_;
    public boolean hasFirstPhaseResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage getFirstPhaseResult() {
      return firstPhaseResult_;
    }
    public waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessageOrBuilder getFirstPhaseResultOrBuilder() {
      return firstPhaseResult_;
    }
    
    // optional .PartnerBackoutCommitRequest backout_commit_request = 4;
    public static final int BACKOUT_COMMIT_REQUEST_FIELD_NUMBER = 4;
    private waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest backoutCommitRequest_;
    public boolean hasBackoutCommitRequest() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest getBackoutCommitRequest() {
      return backoutCommitRequest_;
    }
    public waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequestOrBuilder getBackoutCommitRequestOrBuilder() {
      return backoutCommitRequest_;
    }
    
    // optional .PartnerCompleteCommitRequest complete_commit_request = 5;
    public static final int COMPLETE_COMMIT_REQUEST_FIELD_NUMBER = 5;
    private waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest completeCommitRequest_;
    public boolean hasCompleteCommitRequest() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest getCompleteCommitRequest() {
      return completeCommitRequest_;
    }
    public waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequestOrBuilder getCompleteCommitRequestOrBuilder() {
      return completeCommitRequest_;
    }
    
    // optional .PartnerCommitRequest commit_request = 6;
    public static final int COMMIT_REQUEST_FIELD_NUMBER = 6;
    private waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest commitRequest_;
    public boolean hasCommitRequest() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest getCommitRequest() {
      return commitRequest_;
    }
    public waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequestOrBuilder getCommitRequestOrBuilder() {
      return commitRequest_;
    }
    
    // optional .PartnerStop stop = 7;
    public static final int STOP_FIELD_NUMBER = 7;
    private waldo_protobuffs.PartnerStopProto.PartnerStop stop_;
    public boolean hasStop() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public waldo_protobuffs.PartnerStopProto.PartnerStop getStop() {
      return stop_;
    }
    public waldo_protobuffs.PartnerStopProto.PartnerStopOrBuilder getStopOrBuilder() {
      return stop_;
    }
    
    // optional .PartnerError error = 8;
    public static final int ERROR_FIELD_NUMBER = 8;
    private waldo_protobuffs.PartnerErrorProto.PartnerError error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public waldo_protobuffs.PartnerErrorProto.PartnerError getError() {
      return error_;
    }
    public waldo_protobuffs.PartnerErrorProto.PartnerErrorOrBuilder getErrorOrBuilder() {
      return error_;
    }
    
    // optional .Heartbeat heartbeat = 9;
    public static final int HEARTBEAT_FIELD_NUMBER = 9;
    private waldo_protobuffs.HeartbeatProto.Heartbeat heartbeat_;
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public waldo_protobuffs.HeartbeatProto.Heartbeat getHeartbeat() {
      return heartbeat_;
    }
    public waldo_protobuffs.HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      return heartbeat_;
    }
    
    // optional .Promotion promotion = 10;
    public static final int PROMOTION_FIELD_NUMBER = 10;
    private waldo_protobuffs.PromotionProto.Promotion promotion_;
    public boolean hasPromotion() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public waldo_protobuffs.PromotionProto.Promotion getPromotion() {
      return promotion_;
    }
    public waldo_protobuffs.PromotionProto.PromotionOrBuilder getPromotionOrBuilder() {
      return promotion_;
    }
    
    // required uint64 timestamp = 11;
    public static final int TIMESTAMP_FIELD_NUMBER = 11;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    private void initFields() {
      notifyReady_ = waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.getDefaultInstance();
      requestSequenceBlock_ = waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
      firstPhaseResult_ = waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.getDefaultInstance();
      backoutCommitRequest_ = waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.getDefaultInstance();
      completeCommitRequest_ = waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.getDefaultInstance();
      commitRequest_ = waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.getDefaultInstance();
      stop_ = waldo_protobuffs.PartnerStopProto.PartnerStop.getDefaultInstance();
      error_ = waldo_protobuffs.PartnerErrorProto.PartnerError.getDefaultInstance();
      heartbeat_ = waldo_protobuffs.HeartbeatProto.Heartbeat.getDefaultInstance();
      promotion_ = waldo_protobuffs.PromotionProto.Promotion.getDefaultInstance();
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasNotifyReady()) {
        if (!getNotifyReady().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRequestSequenceBlock()) {
        if (!getRequestSequenceBlock().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasFirstPhaseResult()) {
        if (!getFirstPhaseResult().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBackoutCommitRequest()) {
        if (!getBackoutCommitRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCompleteCommitRequest()) {
        if (!getCompleteCommitRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasCommitRequest()) {
        if (!getCommitRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasStop()) {
        if (!getStop().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasError()) {
        if (!getError().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPromotion()) {
        if (!getPromotion().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, notifyReady_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, requestSequenceBlock_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, firstPhaseResult_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, backoutCommitRequest_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, completeCommitRequest_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, commitRequest_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, stop_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, error_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, heartbeat_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeMessage(10, promotion_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt64(11, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, notifyReady_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, requestSequenceBlock_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, firstPhaseResult_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, backoutCommitRequest_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, completeCommitRequest_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, commitRequest_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, stop_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, error_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, heartbeat_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, promotion_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ralph_protobuffs.GeneralMessageProto.GeneralMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ralph_protobuffs.GeneralMessageProto.GeneralMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ralph_protobuffs.GeneralMessageProto.GeneralMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ralph_protobuffs.GeneralMessageProto.internal_static_GeneralMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ralph_protobuffs.GeneralMessageProto.internal_static_GeneralMessage_fieldAccessorTable;
      }
      
      // Construct using ralph_protobuffs.GeneralMessageProto.GeneralMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNotifyReadyFieldBuilder();
          getRequestSequenceBlockFieldBuilder();
          getFirstPhaseResultFieldBuilder();
          getBackoutCommitRequestFieldBuilder();
          getCompleteCommitRequestFieldBuilder();
          getCommitRequestFieldBuilder();
          getStopFieldBuilder();
          getErrorFieldBuilder();
          getHeartbeatFieldBuilder();
          getPromotionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (notifyReadyBuilder_ == null) {
          notifyReady_ = waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.getDefaultInstance();
        } else {
          notifyReadyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (requestSequenceBlockBuilder_ == null) {
          requestSequenceBlock_ = waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
        } else {
          requestSequenceBlockBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (firstPhaseResultBuilder_ == null) {
          firstPhaseResult_ = waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.getDefaultInstance();
        } else {
          firstPhaseResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (backoutCommitRequestBuilder_ == null) {
          backoutCommitRequest_ = waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.getDefaultInstance();
        } else {
          backoutCommitRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (completeCommitRequestBuilder_ == null) {
          completeCommitRequest_ = waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.getDefaultInstance();
        } else {
          completeCommitRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (commitRequestBuilder_ == null) {
          commitRequest_ = waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.getDefaultInstance();
        } else {
          commitRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (stopBuilder_ == null) {
          stop_ = waldo_protobuffs.PartnerStopProto.PartnerStop.getDefaultInstance();
        } else {
          stopBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (errorBuilder_ == null) {
          error_ = waldo_protobuffs.PartnerErrorProto.PartnerError.getDefaultInstance();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        if (heartbeatBuilder_ == null) {
          heartbeat_ = waldo_protobuffs.HeartbeatProto.Heartbeat.getDefaultInstance();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        if (promotionBuilder_ == null) {
          promotion_ = waldo_protobuffs.PromotionProto.Promotion.getDefaultInstance();
        } else {
          promotionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ralph_protobuffs.GeneralMessageProto.GeneralMessage.getDescriptor();
      }
      
      public ralph_protobuffs.GeneralMessageProto.GeneralMessage getDefaultInstanceForType() {
        return ralph_protobuffs.GeneralMessageProto.GeneralMessage.getDefaultInstance();
      }
      
      public ralph_protobuffs.GeneralMessageProto.GeneralMessage build() {
        ralph_protobuffs.GeneralMessageProto.GeneralMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ralph_protobuffs.GeneralMessageProto.GeneralMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ralph_protobuffs.GeneralMessageProto.GeneralMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ralph_protobuffs.GeneralMessageProto.GeneralMessage buildPartial() {
        ralph_protobuffs.GeneralMessageProto.GeneralMessage result = new ralph_protobuffs.GeneralMessageProto.GeneralMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (notifyReadyBuilder_ == null) {
          result.notifyReady_ = notifyReady_;
        } else {
          result.notifyReady_ = notifyReadyBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (requestSequenceBlockBuilder_ == null) {
          result.requestSequenceBlock_ = requestSequenceBlock_;
        } else {
          result.requestSequenceBlock_ = requestSequenceBlockBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (firstPhaseResultBuilder_ == null) {
          result.firstPhaseResult_ = firstPhaseResult_;
        } else {
          result.firstPhaseResult_ = firstPhaseResultBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (backoutCommitRequestBuilder_ == null) {
          result.backoutCommitRequest_ = backoutCommitRequest_;
        } else {
          result.backoutCommitRequest_ = backoutCommitRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (completeCommitRequestBuilder_ == null) {
          result.completeCommitRequest_ = completeCommitRequest_;
        } else {
          result.completeCommitRequest_ = completeCommitRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (commitRequestBuilder_ == null) {
          result.commitRequest_ = commitRequest_;
        } else {
          result.commitRequest_ = commitRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (stopBuilder_ == null) {
          result.stop_ = stop_;
        } else {
          result.stop_ = stopBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (heartbeatBuilder_ == null) {
          result.heartbeat_ = heartbeat_;
        } else {
          result.heartbeat_ = heartbeatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        if (promotionBuilder_ == null) {
          result.promotion_ = promotion_;
        } else {
          result.promotion_ = promotionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ralph_protobuffs.GeneralMessageProto.GeneralMessage) {
          return mergeFrom((ralph_protobuffs.GeneralMessageProto.GeneralMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ralph_protobuffs.GeneralMessageProto.GeneralMessage other) {
        if (other == ralph_protobuffs.GeneralMessageProto.GeneralMessage.getDefaultInstance()) return this;
        if (other.hasNotifyReady()) {
          mergeNotifyReady(other.getNotifyReady());
        }
        if (other.hasRequestSequenceBlock()) {
          mergeRequestSequenceBlock(other.getRequestSequenceBlock());
        }
        if (other.hasFirstPhaseResult()) {
          mergeFirstPhaseResult(other.getFirstPhaseResult());
        }
        if (other.hasBackoutCommitRequest()) {
          mergeBackoutCommitRequest(other.getBackoutCommitRequest());
        }
        if (other.hasCompleteCommitRequest()) {
          mergeCompleteCommitRequest(other.getCompleteCommitRequest());
        }
        if (other.hasCommitRequest()) {
          mergeCommitRequest(other.getCommitRequest());
        }
        if (other.hasStop()) {
          mergeStop(other.getStop());
        }
        if (other.hasError()) {
          mergeError(other.getError());
        }
        if (other.hasHeartbeat()) {
          mergeHeartbeat(other.getHeartbeat());
        }
        if (other.hasPromotion()) {
          mergePromotion(other.getPromotion());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (hasNotifyReady()) {
          if (!getNotifyReady().isInitialized()) {
            
            return false;
          }
        }
        if (hasRequestSequenceBlock()) {
          if (!getRequestSequenceBlock().isInitialized()) {
            
            return false;
          }
        }
        if (hasFirstPhaseResult()) {
          if (!getFirstPhaseResult().isInitialized()) {
            
            return false;
          }
        }
        if (hasBackoutCommitRequest()) {
          if (!getBackoutCommitRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasCompleteCommitRequest()) {
          if (!getCompleteCommitRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasCommitRequest()) {
          if (!getCommitRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasStop()) {
          if (!getStop().isInitialized()) {
            
            return false;
          }
        }
        if (hasError()) {
          if (!getError().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {
            
            return false;
          }
        }
        if (hasPromotion()) {
          if (!getPromotion().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.Builder subBuilder = waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.newBuilder();
              if (hasNotifyReady()) {
                subBuilder.mergeFrom(getNotifyReady());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNotifyReady(subBuilder.buildPartial());
              break;
            }
            case 18: {
              waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder subBuilder = waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.newBuilder();
              if (hasRequestSequenceBlock()) {
                subBuilder.mergeFrom(getRequestSequenceBlock());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRequestSequenceBlock(subBuilder.buildPartial());
              break;
            }
            case 26: {
              waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.Builder subBuilder = waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.newBuilder();
              if (hasFirstPhaseResult()) {
                subBuilder.mergeFrom(getFirstPhaseResult());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFirstPhaseResult(subBuilder.buildPartial());
              break;
            }
            case 34: {
              waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.Builder subBuilder = waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.newBuilder();
              if (hasBackoutCommitRequest()) {
                subBuilder.mergeFrom(getBackoutCommitRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBackoutCommitRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.Builder subBuilder = waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.newBuilder();
              if (hasCompleteCommitRequest()) {
                subBuilder.mergeFrom(getCompleteCommitRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCompleteCommitRequest(subBuilder.buildPartial());
              break;
            }
            case 50: {
              waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.Builder subBuilder = waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.newBuilder();
              if (hasCommitRequest()) {
                subBuilder.mergeFrom(getCommitRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommitRequest(subBuilder.buildPartial());
              break;
            }
            case 58: {
              waldo_protobuffs.PartnerStopProto.PartnerStop.Builder subBuilder = waldo_protobuffs.PartnerStopProto.PartnerStop.newBuilder();
              if (hasStop()) {
                subBuilder.mergeFrom(getStop());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStop(subBuilder.buildPartial());
              break;
            }
            case 66: {
              waldo_protobuffs.PartnerErrorProto.PartnerError.Builder subBuilder = waldo_protobuffs.PartnerErrorProto.PartnerError.newBuilder();
              if (hasError()) {
                subBuilder.mergeFrom(getError());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setError(subBuilder.buildPartial());
              break;
            }
            case 74: {
              waldo_protobuffs.HeartbeatProto.Heartbeat.Builder subBuilder = waldo_protobuffs.HeartbeatProto.Heartbeat.newBuilder();
              if (hasHeartbeat()) {
                subBuilder.mergeFrom(getHeartbeat());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeartbeat(subBuilder.buildPartial());
              break;
            }
            case 82: {
              waldo_protobuffs.PromotionProto.Promotion.Builder subBuilder = waldo_protobuffs.PromotionProto.Promotion.newBuilder();
              if (hasPromotion()) {
                subBuilder.mergeFrom(getPromotion());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPromotion(subBuilder.buildPartial());
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              timestamp_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .PartnerNotifyReady notify_ready = 1;
      private waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady notifyReady_ = waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady, waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.Builder, waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReadyOrBuilder> notifyReadyBuilder_;
      public boolean hasNotifyReady() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady getNotifyReady() {
        if (notifyReadyBuilder_ == null) {
          return notifyReady_;
        } else {
          return notifyReadyBuilder_.getMessage();
        }
      }
      public Builder setNotifyReady(waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady value) {
        if (notifyReadyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notifyReady_ = value;
          onChanged();
        } else {
          notifyReadyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setNotifyReady(
          waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.Builder builderForValue) {
        if (notifyReadyBuilder_ == null) {
          notifyReady_ = builderForValue.build();
          onChanged();
        } else {
          notifyReadyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeNotifyReady(waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady value) {
        if (notifyReadyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              notifyReady_ != waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.getDefaultInstance()) {
            notifyReady_ =
              waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.newBuilder(notifyReady_).mergeFrom(value).buildPartial();
          } else {
            notifyReady_ = value;
          }
          onChanged();
        } else {
          notifyReadyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearNotifyReady() {
        if (notifyReadyBuilder_ == null) {
          notifyReady_ = waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.getDefaultInstance();
          onChanged();
        } else {
          notifyReadyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.Builder getNotifyReadyBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getNotifyReadyFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReadyOrBuilder getNotifyReadyOrBuilder() {
        if (notifyReadyBuilder_ != null) {
          return notifyReadyBuilder_.getMessageOrBuilder();
        } else {
          return notifyReady_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady, waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.Builder, waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReadyOrBuilder> 
          getNotifyReadyFieldBuilder() {
        if (notifyReadyBuilder_ == null) {
          notifyReadyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady, waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReady.Builder, waldo_protobuffs.PartnerNotifyReadyProto.PartnerNotifyReadyOrBuilder>(
                  notifyReady_,
                  getParentForChildren(),
                  isClean());
          notifyReady_ = null;
        }
        return notifyReadyBuilder_;
      }
      
      // optional .PartnerRequestSequenceBlock request_sequence_block = 2;
      private waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock requestSequenceBlock_ = waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock, waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder, waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder> requestSequenceBlockBuilder_;
      public boolean hasRequestSequenceBlock() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock getRequestSequenceBlock() {
        if (requestSequenceBlockBuilder_ == null) {
          return requestSequenceBlock_;
        } else {
          return requestSequenceBlockBuilder_.getMessage();
        }
      }
      public Builder setRequestSequenceBlock(waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock value) {
        if (requestSequenceBlockBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          requestSequenceBlock_ = value;
          onChanged();
        } else {
          requestSequenceBlockBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setRequestSequenceBlock(
          waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder builderForValue) {
        if (requestSequenceBlockBuilder_ == null) {
          requestSequenceBlock_ = builderForValue.build();
          onChanged();
        } else {
          requestSequenceBlockBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeRequestSequenceBlock(waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock value) {
        if (requestSequenceBlockBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              requestSequenceBlock_ != waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance()) {
            requestSequenceBlock_ =
              waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.newBuilder(requestSequenceBlock_).mergeFrom(value).buildPartial();
          } else {
            requestSequenceBlock_ = value;
          }
          onChanged();
        } else {
          requestSequenceBlockBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearRequestSequenceBlock() {
        if (requestSequenceBlockBuilder_ == null) {
          requestSequenceBlock_ = waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.getDefaultInstance();
          onChanged();
        } else {
          requestSequenceBlockBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder getRequestSequenceBlockBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRequestSequenceBlockFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder getRequestSequenceBlockOrBuilder() {
        if (requestSequenceBlockBuilder_ != null) {
          return requestSequenceBlockBuilder_.getMessageOrBuilder();
        } else {
          return requestSequenceBlock_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock, waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder, waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder> 
          getRequestSequenceBlockFieldBuilder() {
        if (requestSequenceBlockBuilder_ == null) {
          requestSequenceBlockBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock, waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlock.Builder, waldo_protobuffs.PartnerRequestSequenceBlockProto.PartnerRequestSequenceBlockOrBuilder>(
                  requestSequenceBlock_,
                  getParentForChildren(),
                  isClean());
          requestSequenceBlock_ = null;
        }
        return requestSequenceBlockBuilder_;
      }
      
      // optional .PartnerFirstPhaseResultMessage first_phase_result = 3;
      private waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage firstPhaseResult_ = waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage, waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.Builder, waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessageOrBuilder> firstPhaseResultBuilder_;
      public boolean hasFirstPhaseResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage getFirstPhaseResult() {
        if (firstPhaseResultBuilder_ == null) {
          return firstPhaseResult_;
        } else {
          return firstPhaseResultBuilder_.getMessage();
        }
      }
      public Builder setFirstPhaseResult(waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage value) {
        if (firstPhaseResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          firstPhaseResult_ = value;
          onChanged();
        } else {
          firstPhaseResultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setFirstPhaseResult(
          waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.Builder builderForValue) {
        if (firstPhaseResultBuilder_ == null) {
          firstPhaseResult_ = builderForValue.build();
          onChanged();
        } else {
          firstPhaseResultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeFirstPhaseResult(waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage value) {
        if (firstPhaseResultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              firstPhaseResult_ != waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.getDefaultInstance()) {
            firstPhaseResult_ =
              waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.newBuilder(firstPhaseResult_).mergeFrom(value).buildPartial();
          } else {
            firstPhaseResult_ = value;
          }
          onChanged();
        } else {
          firstPhaseResultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearFirstPhaseResult() {
        if (firstPhaseResultBuilder_ == null) {
          firstPhaseResult_ = waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.getDefaultInstance();
          onChanged();
        } else {
          firstPhaseResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.Builder getFirstPhaseResultBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFirstPhaseResultFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessageOrBuilder getFirstPhaseResultOrBuilder() {
        if (firstPhaseResultBuilder_ != null) {
          return firstPhaseResultBuilder_.getMessageOrBuilder();
        } else {
          return firstPhaseResult_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage, waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.Builder, waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessageOrBuilder> 
          getFirstPhaseResultFieldBuilder() {
        if (firstPhaseResultBuilder_ == null) {
          firstPhaseResultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage, waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessage.Builder, waldo_protobuffs.PartnerFirstPhaseResultMessageProto.PartnerFirstPhaseResultMessageOrBuilder>(
                  firstPhaseResult_,
                  getParentForChildren(),
                  isClean());
          firstPhaseResult_ = null;
        }
        return firstPhaseResultBuilder_;
      }
      
      // optional .PartnerBackoutCommitRequest backout_commit_request = 4;
      private waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest backoutCommitRequest_ = waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest, waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.Builder, waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequestOrBuilder> backoutCommitRequestBuilder_;
      public boolean hasBackoutCommitRequest() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest getBackoutCommitRequest() {
        if (backoutCommitRequestBuilder_ == null) {
          return backoutCommitRequest_;
        } else {
          return backoutCommitRequestBuilder_.getMessage();
        }
      }
      public Builder setBackoutCommitRequest(waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest value) {
        if (backoutCommitRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          backoutCommitRequest_ = value;
          onChanged();
        } else {
          backoutCommitRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setBackoutCommitRequest(
          waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.Builder builderForValue) {
        if (backoutCommitRequestBuilder_ == null) {
          backoutCommitRequest_ = builderForValue.build();
          onChanged();
        } else {
          backoutCommitRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeBackoutCommitRequest(waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest value) {
        if (backoutCommitRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              backoutCommitRequest_ != waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.getDefaultInstance()) {
            backoutCommitRequest_ =
              waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.newBuilder(backoutCommitRequest_).mergeFrom(value).buildPartial();
          } else {
            backoutCommitRequest_ = value;
          }
          onChanged();
        } else {
          backoutCommitRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearBackoutCommitRequest() {
        if (backoutCommitRequestBuilder_ == null) {
          backoutCommitRequest_ = waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.getDefaultInstance();
          onChanged();
        } else {
          backoutCommitRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.Builder getBackoutCommitRequestBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getBackoutCommitRequestFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequestOrBuilder getBackoutCommitRequestOrBuilder() {
        if (backoutCommitRequestBuilder_ != null) {
          return backoutCommitRequestBuilder_.getMessageOrBuilder();
        } else {
          return backoutCommitRequest_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest, waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.Builder, waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequestOrBuilder> 
          getBackoutCommitRequestFieldBuilder() {
        if (backoutCommitRequestBuilder_ == null) {
          backoutCommitRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest, waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequest.Builder, waldo_protobuffs.PartnerBackoutCommitRequestProto.PartnerBackoutCommitRequestOrBuilder>(
                  backoutCommitRequest_,
                  getParentForChildren(),
                  isClean());
          backoutCommitRequest_ = null;
        }
        return backoutCommitRequestBuilder_;
      }
      
      // optional .PartnerCompleteCommitRequest complete_commit_request = 5;
      private waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest completeCommitRequest_ = waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest, waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.Builder, waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequestOrBuilder> completeCommitRequestBuilder_;
      public boolean hasCompleteCommitRequest() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest getCompleteCommitRequest() {
        if (completeCommitRequestBuilder_ == null) {
          return completeCommitRequest_;
        } else {
          return completeCommitRequestBuilder_.getMessage();
        }
      }
      public Builder setCompleteCommitRequest(waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest value) {
        if (completeCommitRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          completeCommitRequest_ = value;
          onChanged();
        } else {
          completeCommitRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setCompleteCommitRequest(
          waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.Builder builderForValue) {
        if (completeCommitRequestBuilder_ == null) {
          completeCommitRequest_ = builderForValue.build();
          onChanged();
        } else {
          completeCommitRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeCompleteCommitRequest(waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest value) {
        if (completeCommitRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              completeCommitRequest_ != waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.getDefaultInstance()) {
            completeCommitRequest_ =
              waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.newBuilder(completeCommitRequest_).mergeFrom(value).buildPartial();
          } else {
            completeCommitRequest_ = value;
          }
          onChanged();
        } else {
          completeCommitRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearCompleteCommitRequest() {
        if (completeCommitRequestBuilder_ == null) {
          completeCommitRequest_ = waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.getDefaultInstance();
          onChanged();
        } else {
          completeCommitRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.Builder getCompleteCommitRequestBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getCompleteCommitRequestFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequestOrBuilder getCompleteCommitRequestOrBuilder() {
        if (completeCommitRequestBuilder_ != null) {
          return completeCommitRequestBuilder_.getMessageOrBuilder();
        } else {
          return completeCommitRequest_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest, waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.Builder, waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequestOrBuilder> 
          getCompleteCommitRequestFieldBuilder() {
        if (completeCommitRequestBuilder_ == null) {
          completeCommitRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest, waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequest.Builder, waldo_protobuffs.PartnerCompleteCommitRequestProto.PartnerCompleteCommitRequestOrBuilder>(
                  completeCommitRequest_,
                  getParentForChildren(),
                  isClean());
          completeCommitRequest_ = null;
        }
        return completeCommitRequestBuilder_;
      }
      
      // optional .PartnerCommitRequest commit_request = 6;
      private waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest commitRequest_ = waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest, waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.Builder, waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequestOrBuilder> commitRequestBuilder_;
      public boolean hasCommitRequest() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest getCommitRequest() {
        if (commitRequestBuilder_ == null) {
          return commitRequest_;
        } else {
          return commitRequestBuilder_.getMessage();
        }
      }
      public Builder setCommitRequest(waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest value) {
        if (commitRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commitRequest_ = value;
          onChanged();
        } else {
          commitRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setCommitRequest(
          waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.Builder builderForValue) {
        if (commitRequestBuilder_ == null) {
          commitRequest_ = builderForValue.build();
          onChanged();
        } else {
          commitRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeCommitRequest(waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest value) {
        if (commitRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              commitRequest_ != waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.getDefaultInstance()) {
            commitRequest_ =
              waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.newBuilder(commitRequest_).mergeFrom(value).buildPartial();
          } else {
            commitRequest_ = value;
          }
          onChanged();
        } else {
          commitRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearCommitRequest() {
        if (commitRequestBuilder_ == null) {
          commitRequest_ = waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.getDefaultInstance();
          onChanged();
        } else {
          commitRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      public waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.Builder getCommitRequestBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getCommitRequestFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequestOrBuilder getCommitRequestOrBuilder() {
        if (commitRequestBuilder_ != null) {
          return commitRequestBuilder_.getMessageOrBuilder();
        } else {
          return commitRequest_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest, waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.Builder, waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequestOrBuilder> 
          getCommitRequestFieldBuilder() {
        if (commitRequestBuilder_ == null) {
          commitRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest, waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequest.Builder, waldo_protobuffs.PartnerCommitRequestProto.PartnerCommitRequestOrBuilder>(
                  commitRequest_,
                  getParentForChildren(),
                  isClean());
          commitRequest_ = null;
        }
        return commitRequestBuilder_;
      }
      
      // optional .PartnerStop stop = 7;
      private waldo_protobuffs.PartnerStopProto.PartnerStop stop_ = waldo_protobuffs.PartnerStopProto.PartnerStop.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerStopProto.PartnerStop, waldo_protobuffs.PartnerStopProto.PartnerStop.Builder, waldo_protobuffs.PartnerStopProto.PartnerStopOrBuilder> stopBuilder_;
      public boolean hasStop() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public waldo_protobuffs.PartnerStopProto.PartnerStop getStop() {
        if (stopBuilder_ == null) {
          return stop_;
        } else {
          return stopBuilder_.getMessage();
        }
      }
      public Builder setStop(waldo_protobuffs.PartnerStopProto.PartnerStop value) {
        if (stopBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stop_ = value;
          onChanged();
        } else {
          stopBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder setStop(
          waldo_protobuffs.PartnerStopProto.PartnerStop.Builder builderForValue) {
        if (stopBuilder_ == null) {
          stop_ = builderForValue.build();
          onChanged();
        } else {
          stopBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder mergeStop(waldo_protobuffs.PartnerStopProto.PartnerStop value) {
        if (stopBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              stop_ != waldo_protobuffs.PartnerStopProto.PartnerStop.getDefaultInstance()) {
            stop_ =
              waldo_protobuffs.PartnerStopProto.PartnerStop.newBuilder(stop_).mergeFrom(value).buildPartial();
          } else {
            stop_ = value;
          }
          onChanged();
        } else {
          stopBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      public Builder clearStop() {
        if (stopBuilder_ == null) {
          stop_ = waldo_protobuffs.PartnerStopProto.PartnerStop.getDefaultInstance();
          onChanged();
        } else {
          stopBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      public waldo_protobuffs.PartnerStopProto.PartnerStop.Builder getStopBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getStopFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerStopProto.PartnerStopOrBuilder getStopOrBuilder() {
        if (stopBuilder_ != null) {
          return stopBuilder_.getMessageOrBuilder();
        } else {
          return stop_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerStopProto.PartnerStop, waldo_protobuffs.PartnerStopProto.PartnerStop.Builder, waldo_protobuffs.PartnerStopProto.PartnerStopOrBuilder> 
          getStopFieldBuilder() {
        if (stopBuilder_ == null) {
          stopBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerStopProto.PartnerStop, waldo_protobuffs.PartnerStopProto.PartnerStop.Builder, waldo_protobuffs.PartnerStopProto.PartnerStopOrBuilder>(
                  stop_,
                  getParentForChildren(),
                  isClean());
          stop_ = null;
        }
        return stopBuilder_;
      }
      
      // optional .PartnerError error = 8;
      private waldo_protobuffs.PartnerErrorProto.PartnerError error_ = waldo_protobuffs.PartnerErrorProto.PartnerError.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerErrorProto.PartnerError, waldo_protobuffs.PartnerErrorProto.PartnerError.Builder, waldo_protobuffs.PartnerErrorProto.PartnerErrorOrBuilder> errorBuilder_;
      public boolean hasError() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public waldo_protobuffs.PartnerErrorProto.PartnerError getError() {
        if (errorBuilder_ == null) {
          return error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      public Builder setError(waldo_protobuffs.PartnerErrorProto.PartnerError value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder setError(
          waldo_protobuffs.PartnerErrorProto.PartnerError.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder mergeError(waldo_protobuffs.PartnerErrorProto.PartnerError value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              error_ != waldo_protobuffs.PartnerErrorProto.PartnerError.getDefaultInstance()) {
            error_ =
              waldo_protobuffs.PartnerErrorProto.PartnerError.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = waldo_protobuffs.PartnerErrorProto.PartnerError.getDefaultInstance();
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      public waldo_protobuffs.PartnerErrorProto.PartnerError.Builder getErrorBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PartnerErrorProto.PartnerErrorOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PartnerErrorProto.PartnerError, waldo_protobuffs.PartnerErrorProto.PartnerError.Builder, waldo_protobuffs.PartnerErrorProto.PartnerErrorOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PartnerErrorProto.PartnerError, waldo_protobuffs.PartnerErrorProto.PartnerError.Builder, waldo_protobuffs.PartnerErrorProto.PartnerErrorOrBuilder>(
                  error_,
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }
      
      // optional .Heartbeat heartbeat = 9;
      private waldo_protobuffs.HeartbeatProto.Heartbeat heartbeat_ = waldo_protobuffs.HeartbeatProto.Heartbeat.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.HeartbeatProto.Heartbeat, waldo_protobuffs.HeartbeatProto.Heartbeat.Builder, waldo_protobuffs.HeartbeatProto.HeartbeatOrBuilder> heartbeatBuilder_;
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public waldo_protobuffs.HeartbeatProto.Heartbeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          return heartbeat_;
        } else {
          return heartbeatBuilder_.getMessage();
        }
      }
      public Builder setHeartbeat(waldo_protobuffs.HeartbeatProto.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeat_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder setHeartbeat(
          waldo_protobuffs.HeartbeatProto.Heartbeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder mergeHeartbeat(waldo_protobuffs.HeartbeatProto.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              heartbeat_ != waldo_protobuffs.HeartbeatProto.Heartbeat.getDefaultInstance()) {
            heartbeat_ =
              waldo_protobuffs.HeartbeatProto.Heartbeat.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
          } else {
            heartbeat_ = value;
          }
          onChanged();
        } else {
          heartbeatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = waldo_protobuffs.HeartbeatProto.Heartbeat.getDefaultInstance();
          onChanged();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      public waldo_protobuffs.HeartbeatProto.Heartbeat.Builder getHeartbeatBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getHeartbeatFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.HeartbeatProto.HeartbeatOrBuilder getHeartbeatOrBuilder() {
        if (heartbeatBuilder_ != null) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          return heartbeat_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.HeartbeatProto.Heartbeat, waldo_protobuffs.HeartbeatProto.Heartbeat.Builder, waldo_protobuffs.HeartbeatProto.HeartbeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.HeartbeatProto.Heartbeat, waldo_protobuffs.HeartbeatProto.Heartbeat.Builder, waldo_protobuffs.HeartbeatProto.HeartbeatOrBuilder>(
                  heartbeat_,
                  getParentForChildren(),
                  isClean());
          heartbeat_ = null;
        }
        return heartbeatBuilder_;
      }
      
      // optional .Promotion promotion = 10;
      private waldo_protobuffs.PromotionProto.Promotion promotion_ = waldo_protobuffs.PromotionProto.Promotion.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PromotionProto.Promotion, waldo_protobuffs.PromotionProto.Promotion.Builder, waldo_protobuffs.PromotionProto.PromotionOrBuilder> promotionBuilder_;
      public boolean hasPromotion() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public waldo_protobuffs.PromotionProto.Promotion getPromotion() {
        if (promotionBuilder_ == null) {
          return promotion_;
        } else {
          return promotionBuilder_.getMessage();
        }
      }
      public Builder setPromotion(waldo_protobuffs.PromotionProto.Promotion value) {
        if (promotionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          promotion_ = value;
          onChanged();
        } else {
          promotionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder setPromotion(
          waldo_protobuffs.PromotionProto.Promotion.Builder builderForValue) {
        if (promotionBuilder_ == null) {
          promotion_ = builderForValue.build();
          onChanged();
        } else {
          promotionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder mergePromotion(waldo_protobuffs.PromotionProto.Promotion value) {
        if (promotionBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200) &&
              promotion_ != waldo_protobuffs.PromotionProto.Promotion.getDefaultInstance()) {
            promotion_ =
              waldo_protobuffs.PromotionProto.Promotion.newBuilder(promotion_).mergeFrom(value).buildPartial();
          } else {
            promotion_ = value;
          }
          onChanged();
        } else {
          promotionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000200;
        return this;
      }
      public Builder clearPromotion() {
        if (promotionBuilder_ == null) {
          promotion_ = waldo_protobuffs.PromotionProto.Promotion.getDefaultInstance();
          onChanged();
        } else {
          promotionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }
      public waldo_protobuffs.PromotionProto.Promotion.Builder getPromotionBuilder() {
        bitField0_ |= 0x00000200;
        onChanged();
        return getPromotionFieldBuilder().getBuilder();
      }
      public waldo_protobuffs.PromotionProto.PromotionOrBuilder getPromotionOrBuilder() {
        if (promotionBuilder_ != null) {
          return promotionBuilder_.getMessageOrBuilder();
        } else {
          return promotion_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          waldo_protobuffs.PromotionProto.Promotion, waldo_protobuffs.PromotionProto.Promotion.Builder, waldo_protobuffs.PromotionProto.PromotionOrBuilder> 
          getPromotionFieldBuilder() {
        if (promotionBuilder_ == null) {
          promotionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              waldo_protobuffs.PromotionProto.Promotion, waldo_protobuffs.PromotionProto.Promotion.Builder, waldo_protobuffs.PromotionProto.PromotionOrBuilder>(
                  promotion_,
                  getParentForChildren(),
                  isClean());
          promotion_ = null;
        }
        return promotionBuilder_;
      }
      
      // required uint64 timestamp = 11;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000400;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000400);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:GeneralMessage)
    }
    
    static {
      defaultInstance = new GeneralMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:GeneralMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GeneralMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GeneralMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024generalMessage.proto\032\030partnerNotifyRea" +
      "dy.proto\032!partnerRequestSequenceBlock.pr" +
      "oto\032$partnerFirstPhaseResultMessage.prot" +
      "o\032!partnerBackoutCommitRequest.proto\032\"pa" +
      "rtnerCompleteCommitRequest.proto\032\032partne" +
      "rCommitRequest.proto\032\021partnerStop.proto\032" +
      "\022partnerError.proto\032\017heartbeat.proto\032\026pr" +
      "omotionMessage.proto\032\nutil.proto\"\356\003\n\016Gen" +
      "eralMessage\022)\n\014notify_ready\030\001 \001(\0132\023.Part" +
      "nerNotifyReady\022<\n\026request_sequence_block",
      "\030\002 \001(\0132\034.PartnerRequestSequenceBlock\022;\n\022" +
      "first_phase_result\030\003 \001(\0132\037.PartnerFirstP" +
      "haseResultMessage\022<\n\026backout_commit_requ" +
      "est\030\004 \001(\0132\034.PartnerBackoutCommitRequest\022" +
      ">\n\027complete_commit_request\030\005 \001(\0132\035.Partn" +
      "erCompleteCommitRequest\022-\n\016commit_reques" +
      "t\030\006 \001(\0132\025.PartnerCommitRequest\022\032\n\004stop\030\007" +
      " \001(\0132\014.PartnerStop\022\034\n\005error\030\010 \001(\0132\r.Part" +
      "nerError\022\035\n\theartbeat\030\t \001(\0132\n.Heartbeat\022" +
      "\035\n\tpromotion\030\n \001(\0132\n.Promotion\022\021\n\ttimest",
      "amp\030\013 \002(\004B\'\n\020ralph_protobuffsB\023GeneralMe" +
      "ssageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GeneralMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GeneralMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GeneralMessage_descriptor,
              new java.lang.String[] { "NotifyReady", "RequestSequenceBlock", "FirstPhaseResult", "BackoutCommitRequest", "CompleteCommitRequest", "CommitRequest", "Stop", "Error", "Heartbeat", "Promotion", "Timestamp", },
              ralph_protobuffs.GeneralMessageProto.GeneralMessage.class,
              ralph_protobuffs.GeneralMessageProto.GeneralMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          waldo_protobuffs.PartnerNotifyReadyProto.getDescriptor(),
          waldo_protobuffs.PartnerRequestSequenceBlockProto.getDescriptor(),
          waldo_protobuffs.PartnerFirstPhaseResultMessageProto.getDescriptor(),
          waldo_protobuffs.PartnerBackoutCommitRequestProto.getDescriptor(),
          waldo_protobuffs.PartnerCompleteCommitRequestProto.getDescriptor(),
          waldo_protobuffs.PartnerCommitRequestProto.getDescriptor(),
          waldo_protobuffs.PartnerStopProto.getDescriptor(),
          waldo_protobuffs.PartnerErrorProto.getDescriptor(),
          waldo_protobuffs.HeartbeatProto.getDescriptor(),
          waldo_protobuffs.PromotionProto.getDescriptor(),
          waldo_protobuffs.UtilProto.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
